This notebook breaks out different barcodes into a nice convinient tsvs

Uses environment `biopython`

# Initial loading

Importing and setting up global vars...

In [1]:
import pandas as pd
import os
from umi_tools import UMIClusterer

DATA_ROOT="/home/mcn26/palmer_scratch/raw_recap/cohen_retina"
umi_len=12
pBC_len=8

Load MPRA barcode data into a table.

In [2]:
def break_up_mpra_count(file_name_in):
    # Define expected barcode lengths
    rBC_len = 24
    
    # List to store parsed data
    data = []
    
    # Read file and process lines
    with open(os.path.join(DATA_ROOT, file_name_in)) as fin:
        for line in fin:
            line = line.strip()
            
            # Break off number of occurrences
            parts = line.split(" ")
            assert len(parts) == 2, "Error: multiple spaces"
            num_occurrences = int(parts[0])
            
            # Break off cell barcode
            subparts = parts[1].split("_")
            assert len(subparts) == 2, "Error: multiple underscores"
            cell_barcode = subparts[0]
            assert len(cell_barcode) == 16, "Error: malformed cell barcode"
            
            # Break out remaining barcodes
            barcode_seq = subparts[1]
            assert len(barcode_seq) == 44, "Error: malformed remaining barcode"
            
            umi = barcode_seq[:umi_len]
            pBC = barcode_seq[umi_len:umi_len + pBC_len]
            rBC = barcode_seq[umi_len + pBC_len:]
            
            # Append parsed data
            data.append([num_occurrences, cell_barcode, umi, pBC, rBC])
    
    # Create DataFrame
    df = pd.DataFrame(data, columns=["num_occurrences", "cell_barcode", "umi", "pBC", "rBC"])
    
    return df

# Example usage
mpra_r1 = break_up_mpra_count("counts/retina_mpra_r1.count")
mpra_r2 = break_up_mpra_count("counts/retina_mpra_r2.count")

Take a look...

In [3]:
mpra_r1

,num_occurrences,cell_barcode,umi,pBC,rBC
0,1,AAAAAAAAATCTACAT,AACAACATAATA,TTAAGTGG,TTAATTTTAAAGTTTATGAGTGCT
1,1,AAAAAAAACCCTCTAA,AAATCAATATAA,CGAGGCAA,GTTATTGTAAGCGCTCAAAATGTA
2,1,AAAAAAAAGAATAGAT,ATCACGTGATTA,CAATGGAC,CATCGGTAATCTTCTCGAACAAAA
3,1,AAAAAAAAGACTAGAT,ATTAATCACGAT,CGGAAGGA,CCCTTGGCCATACTGAGTCCGAAT
4,1,AAAAAAAAGACTAGAT,CAATTCAAAGGT,CAAGTATG,TTAGTTTTTGAAAACTACAGGTCG
...,...,...,...,...,...
8572749,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,ATATCACG,CCTGCCCCTTTGTTTAATATACAC
8572750,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,ATGCAACC,TGCTCGTGGGGATCAGACGGTCTA
8572751,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CCTTCGGA,TTTGATATTACATACGGATATCCA
8572752,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CGTGCCAA,TGTGCTCCTTACGTACTAATGAAT
8572753,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,TTCAGTGG,GAACACGTATACCTTAAAGATAAA

In [4]:
mpra_r2

,num_occurrences,cell_barcode,umi,pBC,rBC
0,1,AAAAAAAAAAAAGAGA,ACTGAAAAATCC,ACGTTAAT,CCCAAAAATAATTAAAGAAAATCA
1,1,AAAAAAAAGAAAATTA,TAATACCAGCTA,CGTGCGAA,TAATCTGTGAAAGATCTCGGCATA
2,1,AAAAAAAAGAAATGTA,ATCTCAAACCCT,AAATAGAA,TTTAATGCCGCTTACATATGGAGA
3,1,AAAAAAAAGCGCCAAT,TAAATCTATACG,TTCAGTGG,CGTTGAGAAGTACGTATATACACA
4,1,AAAAAAAAGTATAATA,GAACACAAAAAA,CAGTGGCA,ATAGTAGACTGTGTGAAGATGATG
...,...,...,...,...,...
7376486,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CACATGCT,TCGTTAGTGCTATCGGTTACACCA
7376487,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CAGAACCT,ATATCATGTTTGCCAAACGCGCAT
7376488,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CCTTCGGA,ATCCGCGCTAGTATAGTTCGACCT
7376489,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CGGAAGGA,TTTCGATGACTTAATTGGCATCGT
7376490,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,TTCAGTGG,GAGGGTCGACTAGTGATAAAGAGT

Looks good!

Let's load the u6 data..

In [5]:
def break_up_u6_count(filename):
    #format is
    #leading whitespace, num occurances, space, 16 bp cell-barcode, 12bp UMI, 8 bp pBC
    
    # List to store parsed data
    data = []

    with open(f"{DATA_ROOT}/{filename}") as fin:
        for line in fin:
            original_line=line

            line=line.strip()
            
            #break off number of occurrences
            line=line.split(" ")
            assert len(line) == 2, "err, multiple spaces"
            num_occurrences=int(line[0])

            #break off cell barcode
            line=line[1].split("_")
            assert len(line) == 2, "err, multiple underscore"
            cell_barcode=line[0]
            assert len(cell_barcode)==16, "err, malformed cell barcode"

            #break out remaining barcodes
            line=line[1]
            assert len(line)==20, "err, malformed remaining barcode"
            
            umi=line[:umi_len]
            pBC=line[umi_len:]
            
            data.append([num_occurrences, cell_barcode, umi, pBC])

    
    return pd.DataFrame(data,columns=["num_occurrences","cell_barcode","umi","pBC"])



u6_r1=break_up_u6_count("counts/retina_u6_r1.count")
u6_r2=break_up_u6_count("counts/retina_u6_r2.count")

In [6]:
u6_r1

         num_occurrences      cell_barcode           umi       pBC
0                      1  AAAAAAAAAAAAAAAA  AAAAAAAAAAAA  CGCTAATA
1                      1  AAAAAAAACAAAACAG  AAAAATCTAAAC  CCAAGTCC
2                      1  AAAAAAAACACCAACT  ATACATCAAAAA  AAGGTCGA
3                      1  AAAAAAAACTCTACCA  AATTTAAGTAAA  ACGTGGGG
4                      1  AAAAAAACAAAAAGAA  ATCTTCAGTAAA  CAGCCGAT
...                  ...               ...           ...       ...
4681458                1  TTTTTTGAGGTCGCTT  TTTTAACATACC  CCAATTAC
4681459                2  TTTTTTGCATCAAGTC  AAACACTACATT  CAGCCGAT
4681460                1  TTTTTTGGTATGCTCA  TTCGAACGCTTG  CAGCCGAG
4681461                1  TTTTTTGGTCCATTCC  AAGATTAATGAT  ATAAGAGG
4681462                1  TTTTTTGTCGTCATCT  GGGGGGCCACAC  CAGCCGAT

[4681463 rows x 4 columns]

In [7]:
u6_r2

         num_occurrences      cell_barcode           umi       pBC
0                      1  AAAAAAAAAAAAAAAA  AAAAAAAAAAAA  CGCTAATA
1                      1  AAAAAAAACACCAACT  ATACATCAAAAA  AAGGTCGA
2                      1  AAAAAAAACTCTACCA  AATTTAAGTAAA  ACGTGGGG
3                      1  AAAAAAAAGATCCTAA  AACAAAATTGGC  AGGGATGG
4                      1  AAAAAAAAGTAGACCA  AATAAAAAAAAA  CAGCCGAT
...                  ...               ...           ...       ...
7221247                1  TTTTTTGTCGAGTATT  GGGTAATTAGCC  ATGACGGA
7221248                1  TTTTTTGTCGAGTATT  GTTAGGAAGCGT  CCAATTAC
7221249                1  TTTTTTGTCGAGTATT  TCCCTTGTGATC  ATCGCCGT
7221250                1  TTTTTTGTCGAGTATT  TTCAGTTGAGTA  CGTAGCTT
7221251                1  TTTTTTTCAAAGATTG  ATGTCAGAATCC  AATAGTGG

[7221252 rows x 4 columns]

In [8]:
#stack u6 replicate dfs...
u6_r1["replicate"]="1"
u6_r2["replicate"]="2"
all_u6=pd.concat([u6_r1,u6_r2])

Perfect, now load the list of valid cells and their types...

In [9]:
cell_types=pd.read_csv(f"{DATA_ROOT}/retina_cell_types.tsv",sep="\t",index_col=0)
cell_types.rename({'cbc':'cell_barcode'},axis=1,inplace=True)
cell_types['replicate']=cell_types['replicate']+1
cell_types

           cell_barcode       leiden  replicate
0      AAACCCAAGACAAGCC          Rod          1
1      AAACCCAAGAGATCGC          Rod          1
2      AAACCCAAGCTGAAAT          Rod          1
3      AAACCCAAGTACGTCT          Rod          1
4      AAACCCACAACCCGCA          Rod          1
...                 ...          ...        ...
22152  TTTGTTGGTTTACCAG          Rod          2
22153  TTTGTTGTCACCACAA          Rod          2
22154  TTTGTTGTCGGCAGTC          Rod          2
22155  TTTGTTGTCGTTAGAC  Interneuron          2
22156  TTTGTTGTCGTTCAGA          Rod          2

[22157 rows x 3 columns]

# Filtering main MPRA data

We will merge the cell-type info in. Since this data has gone through filtering, an inner join will filter the MPRA data, dropping bad cells.

Let's stack the MPRA replicates:

In [10]:
mpra_r1["replicate"]="1"
mpra_r2["replicate"]="2"
all_mpra=pd.concat([mpra_r1,mpra_r2])

In [11]:
all_mpra

,num_occurrences,cell_barcode,umi,pBC,rBC,replicate
0,1,AAAAAAAAATCTACAT,AACAACATAATA,TTAAGTGG,TTAATTTTAAAGTTTATGAGTGCT,1
1,1,AAAAAAAACCCTCTAA,AAATCAATATAA,CGAGGCAA,GTTATTGTAAGCGCTCAAAATGTA,1
2,1,AAAAAAAAGAATAGAT,ATCACGTGATTA,CAATGGAC,CATCGGTAATCTTCTCGAACAAAA,1
3,1,AAAAAAAAGACTAGAT,ATTAATCACGAT,CGGAAGGA,CCCTTGGCCATACTGAGTCCGAAT,1
4,1,AAAAAAAAGACTAGAT,CAATTCAAAGGT,CAAGTATG,TTAGTTTTTGAAAACTACAGGTCG,1
...,...,...,...,...,...,...
7376486,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CACATGCT,TCGTTAGTGCTATCGGTTACACCA,2
7376487,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CAGAACCT,ATATCATGTTTGCCAAACGCGCAT,2
7376488,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CCTTCGGA,ATCCGCGCTAGTATAGTTCGACCT,2
7376489,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CGGAAGGA,TTTCGATGACTTAATTGGCATCGT,2
7376490,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,TTCAGTGG,GAGGGTCGACTAGTGATAAAGAGT,2

I want to do inner joins of mpra data and cell-type annotations, but I want to make sure there will be no duplicated entries. So I will make sure all cell-barcode, replicate combinations are unique in the cell type annotation df.

In [12]:
total_celltype_rows=len(cell_types)
unique_celltype_cbc=cell_types.groupby(["cell_barcode","replicate"]).ngroups
assert total_celltype_rows==unique_celltype_cbc

Perfect. Let's do the intersection:

In [13]:
joincols=["cell_barcode","replicate"]

all_mpra=all_mpra.astype({col:str for col in joincols})
cell_types=cell_types.astype({col:str for col in joincols})

inner_mpra=all_mpra.merge(cell_types,on=joincols,how="inner")
inner_mpra

,num_occurrences,cell_barcode,umi,pBC,rBC,replicate,leiden
0,4,AAACCCAAGACAAGCC,ATATTTCGTCAG,ACGTTCAA,ATTATAAAAGATACTCATGAGTCT,1,Rod
1,14,AAACCCAAGACAAGCC,ATCATCCCACCA,CGCCTCAA,TGTTACCTTTTTTTTGTGTGACAT,1,Rod
2,1,AAACCCAAGACAAGCC,ATCATCCCACCA,CGCCTCAA,TGTTACGTTTTTTTTGTGTGACAT,1,Rod
3,5,AAACCCAAGACAAGCC,CAATTTCGTCAG,ACGTTCAA,ATTATAAAAGATACTCATGAGTCT,1,Rod
4,1,AAACCCAAGACAAGCC,CAATTTCGTCAG,CAATGGAC,AAACCTTACCCTTCCTTTACGCGG,1,Rod
...,...,...,...,...,...,...,...
10693076,1,TTTGTTGTCGTTCAGA,GTTACAAGTATT,CAAGTCTG,TAAATGCGGGACAACACAATTTGT,2,Rod
10693077,1,TTTGTTGTCGTTCAGA,TAAGTCCTTCGG,CAGCCGAT,CGTCAACCAGCCCGTCGAATGTAC,2,Rod
10693078,1,TTTGTTGTCGTTCAGA,TGAATTGGCCAG,AATAGTGG,AAATAGGAATCGGGGTCTGACTTG,2,Rod
10693079,5,TTTGTTGTCGTTCAGA,TGCCGCTTAAAT,TTCAGTGG,TTACCTAGCTTTACTCATGAAAAA,2,Rod
10693080,1,TTTGTTGTCGTTCAGA,TTTATAATTGAT,CCTTCGGA,TGCATATCGGAAAAGGGCTAGGGA,2,Rod

In [14]:
print(len(inner_mpra))
print(len(all_mpra))
print(len(cell_types))
print()
print(f"retained={len(inner_mpra)/len(all_mpra)*100}%")

10693081
15949245
22157

retained=67.04443376473307%

Let's check if complementing or reverse-complementing bases 8 & 9 would increase retained % (since this is a feature of some 10x cell-barcodes...):

In [15]:
#some helper functions 
comp = str.maketrans("ACGTacgt", "TGCAtgca")

def comp_mid(nt):
    return nt[0:7]+ nt[7:9].translate(comp) +nt[9:16]

def revcomp_mid(nt):
    return nt[0:7]+ nt[7:9].translate(comp)[::-1] +nt[9:16]

#quick tests
assert "GATCgatcg".translate(comp)=="CTAGctagc"
assert comp_mid("AAAAAAATCAAAAAAA")=="AAAAAAAAGAAAAAAA"
assert revcomp_mid("AAAAAAATCAAAAAAA")=="AAAAAAAGAAAAAAAA"

In [16]:
all_mpra["rc_cbc"]=all_mpra["cell_barcode"].apply(revcomp_mid)
all_mpra["c_cbc"]=all_mpra["cell_barcode"].apply(comp_mid)

In [17]:
#spot-checking..
all_mpra

,num_occurrences,cell_barcode,umi,pBC,rBC,replicate,rc_cbc,c_cbc
0,1,AAAAAAAAATCTACAT,AACAACATAATA,TTAAGTGG,TTAATTTTAAAGTTTATGAGTGCT,1,AAAAAAATTTCTACAT,AAAAAAATTTCTACAT
1,1,AAAAAAAACCCTCTAA,AAATCAATATAA,CGAGGCAA,GTTATTGTAAGCGCTCAAAATGTA,1,AAAAAAAGTCCTCTAA,AAAAAAATGCCTCTAA
2,1,AAAAAAAAGAATAGAT,ATCACGTGATTA,CAATGGAC,CATCGGTAATCTTCTCGAACAAAA,1,AAAAAAACTAATAGAT,AAAAAAATCAATAGAT
3,1,AAAAAAAAGACTAGAT,ATTAATCACGAT,CGGAAGGA,CCCTTGGCCATACTGAGTCCGAAT,1,AAAAAAACTACTAGAT,AAAAAAATCACTAGAT
4,1,AAAAAAAAGACTAGAT,CAATTCAAAGGT,CAAGTATG,TTAGTTTTTGAAAACTACAGGTCG,1,AAAAAAACTACTAGAT,AAAAAAATCACTAGAT
...,...,...,...,...,...,...,...,...
7376486,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CACATGCT,TCGTTAGTGCTATCGGTTACACCA,2,TTTTTTTAATTTTTTT,TTTTTTTAATTTTTTT
7376487,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CAGAACCT,ATATCATGTTTGCCAAACGCGCAT,2,TTTTTTTAATTTTTTT,TTTTTTTAATTTTTTT
7376488,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CCTTCGGA,ATCCGCGCTAGTATAGTTCGACCT,2,TTTTTTTAATTTTTTT,TTTTTTTAATTTTTTT
7376489,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,CGGAAGGA,TTTCGATGACTTAATTGGCATCGT,2,TTTTTTTAATTTTTTT,TTTTTTTAATTTTTTT
7376490,1,TTTTTTTTTTTTTTTT,TTTTTTTTTTTT,TTCAGTGG,GAGGGTCGACTAGTGATAAAGAGT,2,TTTTTTTAATTTTTTT,TTTTTTTAATTTTTTT

In [18]:
rc_height=len(all_mpra.merge(cell_types,left_on=["rc_cbc","replicate"],right_on=["cell_barcode","replicate"],how="inner"))
print(f"retained rc={rc_height/len(all_mpra)*100}%")

c_height=len(all_mpra.merge(cell_types,left_on=["c_cbc","replicate"],right_on=["cell_barcode","replicate"],how="inner"))
print(f"retained c={c_height/len(all_mpra)*100}%")

retained rc=0.0001880966779305227%
retained c=0.03161905156012087%

Clearly the join `inner_mpra` was best... 68% remaining is not so bad a loss. I will go ahead with this for now, and implement a more sophisticated system using the umi-tools API later.

# Filtering U6 data

First thing we need to do is figure out how the barcodes are to be merged in...

In [20]:
all_u6["rc_cbc"]=all_u6["cell_barcode"].apply(revcomp_mid)
all_u6["c_cbc"]=all_u6["cell_barcode"].apply(comp_mid)

inner_u6=all_u6.merge(cell_types,on=["cell_barcode","replicate"],how="inner")
rc_inner_u6=all_u6.merge(cell_types,left_on=["rc_cbc","replicate"],right_on=["cell_barcode","replicate"],how="inner")
c_inner_u6=all_u6.merge(cell_types,left_on=["c_cbc","replicate"],right_on=["cell_barcode","replicate"],how="inner")

print(f"retained={len(inner_u6)/len(all_u6)*100}%")
print(f"retained rc={len(rc_inner_u6)/len(all_u6)*100}%")
print(f"retained c={len(c_inner_u6)/len(all_u6)*100}%")

retained=0.01770184365499804%
retained rc=0.0022263828042593642%
retained c=43.31170661483535%

Plainly the complement is correct! Let's clean up `c_inner_u6` and proceed...

In [21]:
u6=c_inner_u6.drop(["cell_barcode_x","cell_barcode_y","rc_cbc"],axis=1)
u6=u6.rename({"c_cbc":"cell_barcode"},axis=1)

In [22]:
u6

,num_occurrences,umi,pBC,replicate,cell_barcode,leiden
0,34,AAGGCGAGAGAG,ATGGAATG,1,AAACCCATCGCCGAGT,Rod
1,32,ACGCATCTCTTG,CGGTGAGA,1,AAACCCAGTAATCAGA,Rod
2,32,ACTCTACCATAA,AATCTCCA,1,AAACCCAGTAATCAGA,Rod
3,1,AGCCTCACAACC,ATGGAATG,1,AAACCCAGTAATCAGA,Rod
4,22,AGCCTCACAACG,ATGGAATG,1,AAACCCAGTAATCAGA,Rod
...,...,...,...,...,...,...
5155264,26,GTGACTTTCTGT,CGCGTTAC,2,TTTGTTGAGCTGCCAC,Rod
5155265,5,TAATCCAATGTA,CAGATGTG,2,TTTGTTGAGCTGCCAC,Rod
5155266,2,TGCTTTTTACAA,CGTGCCAA,2,TTTGTTGAGCTGCCAC,Rod
5155267,5,TTACAAGTCGCA,ATGGAATG,2,TTTGTTGAGCTGCCAC,Rod
5155268,2,TTGCCCGATACT,AGTGATTC,2,TTTGTTGAGCTGCCAC,Rod

# Add CREid

Now let's add the CRE to each pBC (again, doing this in a rather unsophisticated way, just based on perfect matches)...

In [23]:
#download the supplementary tables.
import urllib
urllib.request.urlretrieve("https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-022-01278-7/MediaObjects/41588_2022_1278_MOESM3_ESM.xlsx",f"{DATA_ROOT}/sup.xlsx")

('/home/mcn26/palmer_scratch/raw_recap/cohen_retina/sup.xlsx',
 <http.client.HTTPMessage at 0x14bb0b05a870>)

In [25]:
CRE_IDs=pd.read_excel(f"{DATA_ROOT}/sup.xlsx",sheet_name="Supplementary Table 5",skiprows=1)
CRE_IDs.drop(["order_name","sequence"],axis=1,inplace=True)
CRE_IDs.rename({'barcode':'pBC'},axis=1,inplace=True)
assert len(CRE_IDs)==len(CRE_IDs["name"].unique())==len(CRE_IDs["pBC"].unique())
CRE_IDs

                          name       pBC
0    ebox_gcagctgg_to_acagctgg  AACAACAC
1    ebox_gcagctgg_to_ccagctgg  AACAAGGT
2    ebox_gcagctgg_to_tcagctgg  AACACTGA
3    ebox_gcagctgg_to_gaagctgg  AACATTCC
4    ebox_gcagctgg_to_ggagctgg  AACCAGCC
..                         ...       ...
110        combo_Q50_crx3_crx2  CGTAACAC
111        combo_Q50_crx3_crx1  CGTAGCTT
112        combo_Q50_crx2_crx1  CGTCTATG
113                       wt_1  CGTTCTCG
114                       wt_2  CTACCGGA

[115 rows x 2 columns]

In [26]:
final_mpra=inner_mpra.merge(CRE_IDs,how="inner",on="pBC")
final_mpra

,num_occurrences,cell_barcode,umi,pBC,rBC,replicate,leiden,name
0,4,AAACCCAAGACAAGCC,ATATTTCGTCAG,ACGTTCAA,ATTATAAAAGATACTCATGAGTCT,1,Rod,tail_conserve1_159_to_164
1,14,AAACCCAAGACAAGCC,ATCATCCCACCA,CGCCTCAA,TGTTACCTTTTTTTTGTGTGACAT,1,Rod,combo_Q50_crx5_crx4
2,1,AAACCCAAGACAAGCC,ATCATCCCACCA,CGCCTCAA,TGTTACGTTTTTTTTGTGTGACAT,1,Rod,combo_Q50_crx5_crx4
3,5,AAACCCAAGACAAGCC,CAATTTCGTCAG,ACGTTCAA,ATTATAAAAGATACTCATGAGTCT,1,Rod,tail_conserve1_159_to_164
4,1,AAACCCAAGACAAGCC,CAATTTCGTCAG,CAATGGAC,AAACCTTACCCTTCCTTTACGCGG,1,Rod,swap_crx3_to_ctaatccc_forward
...,...,...,...,...,...,...,...,...
8913183,1,TTTGTTGTCGTTCAGA,GTATAACTATTT,AGCTCTAA,TCTGTATATTAGAGTTCCGGGCGG,2,Rod,tail_conserve3_235_to_240
8913184,1,TTTGTTGTCGTTCAGA,GTTACAAGTATT,CAAGTCTG,TAAATGCGGGACAACACAATTTGT,2,Rod,swap_crx4_to_ctaatccc_forward
8913185,1,TTTGTTGTCGTTCAGA,TAAGTCCTTCGG,CAGCCGAT,CGTCAACCAGCCCGTCGAATGTAC,2,Rod,swap_crx1_to_gggcttag_reverse
8913186,1,TTTGTTGTCGTTCAGA,TGAATTGGCCAG,AATAGTGG,AAATAGGAATCGGGGTCTGACTTG,2,Rod,ebox_gcagctgg_to_gcagcggg
8913187,1,TTTGTTGTCGTTCAGA,TTTATAATTGAT,CCTTCGGA,TGCATATCGGAAAAGGGCTAGGGA,2,Rod,combo_Q50_crx5

In [28]:
print(f"{len(final_mpra)/len(inner_mpra)*100}% retained")

83.35472255377098% retained

In [29]:
final_u6=u6.merge(CRE_IDs,how="inner",on="pBC")
final_u6

,num_occurrences,umi,pBC,replicate,cell_barcode,leiden,name
0,34,AAGGCGAGAGAG,ATGGAATG,1,AAACCCATCGCCGAGT,Rod,tail_conserve6_483_to_488
1,32,ACGCATCTCTTG,CGGTGAGA,1,AAACCCAGTAATCAGA,Rod,combo_Q50_crx4_crx2
2,32,ACTCTACCATAA,AATCTCCA,1,AAACCCAGTAATCAGA,Rod,ebox_gcagctgg_to_gcagctag
3,1,AGCCTCACAACC,ATGGAATG,1,AAACCCAGTAATCAGA,Rod,tail_conserve6_483_to_488
4,22,AGCCTCACAACG,ATGGAATG,1,AAACCCAGTAATCAGA,Rod,tail_conserve6_483_to_488
...,...,...,...,...,...,...,...
3640103,1,GCAACTCACCAT,CCTGAGTT,2,TTTGTTGAGCTGCCAC,Rod,combo_Mute_crx3_crx1
3640104,1,GTCTGAGGATCC,AGTGATTC,2,TTTGTTGAGCTGCCAC,Rod,tail_conserve4_428_to_433
3640105,26,GTGACTTTCTGT,CGCGTTAC,2,TTTGTTGAGCTGCCAC,Rod,combo_Q50_crx5_crx2
3640106,5,TTACAAGTCGCA,ATGGAATG,2,TTTGTTGAGCTGCCAC,Rod,tail_conserve6_483_to_488
3640107,2,TTGCCCGATACT,AGTGATTC,2,TTTGTTGAGCTGCCAC,Rod,tail_conserve4_428_to_433

In [30]:
print(f"{len(final_u6)/len(u6)*100}% retained")

70.60946771157819% retained

# rename columns & dump to disc

Now let's reformat the table to match our specifications and dump to disc. First the main mpra data

In [35]:
OUTPUT_ROOT="/gpfs/gibbs/pi/reilly/tabula_data/cohen/unjoined"

In [32]:
to_dump_mpra=final_mpra.rename({"num_occurrences":"reads","cell_barcode":"cell_bc","name":"cre_id","leiden":"cell_type","rBC":"mpra_bc","replicate":"rep_id"},axis=1)
to_dump_mpra

,reads,cell_bc,umi,pBC,mpra_bc,rep_id,cell_type,cre_id
0,4,AAACCCAAGACAAGCC,ATATTTCGTCAG,ACGTTCAA,ATTATAAAAGATACTCATGAGTCT,1,Rod,tail_conserve1_159_to_164
1,14,AAACCCAAGACAAGCC,ATCATCCCACCA,CGCCTCAA,TGTTACCTTTTTTTTGTGTGACAT,1,Rod,combo_Q50_crx5_crx4
2,1,AAACCCAAGACAAGCC,ATCATCCCACCA,CGCCTCAA,TGTTACGTTTTTTTTGTGTGACAT,1,Rod,combo_Q50_crx5_crx4
3,5,AAACCCAAGACAAGCC,CAATTTCGTCAG,ACGTTCAA,ATTATAAAAGATACTCATGAGTCT,1,Rod,tail_conserve1_159_to_164
4,1,AAACCCAAGACAAGCC,CAATTTCGTCAG,CAATGGAC,AAACCTTACCCTTCCTTTACGCGG,1,Rod,swap_crx3_to_ctaatccc_forward
...,...,...,...,...,...,...,...,...
8913183,1,TTTGTTGTCGTTCAGA,GTATAACTATTT,AGCTCTAA,TCTGTATATTAGAGTTCCGGGCGG,2,Rod,tail_conserve3_235_to_240
8913184,1,TTTGTTGTCGTTCAGA,GTTACAAGTATT,CAAGTCTG,TAAATGCGGGACAACACAATTTGT,2,Rod,swap_crx4_to_ctaatccc_forward
8913185,1,TTTGTTGTCGTTCAGA,TAAGTCCTTCGG,CAGCCGAT,CGTCAACCAGCCCGTCGAATGTAC,2,Rod,swap_crx1_to_gggcttag_reverse
8913186,1,TTTGTTGTCGTTCAGA,TGAATTGGCCAG,AATAGTGG,AAATAGGAATCGGGGTCTGACTTG,2,Rod,ebox_gcagctgg_to_gcagcggg
8913187,1,TTTGTTGTCGTTCAGA,TTTATAATTGAT,CCTTCGGA,TGCATATCGGAAAAGGGCTAGGGA,2,Rod,combo_Q50_crx5

In [37]:
to_dump_mpra=to_dump_mpra[["cell_bc","rep_id","cre_id","cell_type","mpra_bc","umi","reads"]]
to_dump_mpra

,cell_bc,rep_id,cre_id,cell_type,mpra_bc,umi,reads
0,AAACCCAAGACAAGCC,1,tail_conserve1_159_to_164,Rod,ATTATAAAAGATACTCATGAGTCT,ATATTTCGTCAG,4
1,AAACCCAAGACAAGCC,1,combo_Q50_crx5_crx4,Rod,TGTTACCTTTTTTTTGTGTGACAT,ATCATCCCACCA,14
2,AAACCCAAGACAAGCC,1,combo_Q50_crx5_crx4,Rod,TGTTACGTTTTTTTTGTGTGACAT,ATCATCCCACCA,1
3,AAACCCAAGACAAGCC,1,tail_conserve1_159_to_164,Rod,ATTATAAAAGATACTCATGAGTCT,CAATTTCGTCAG,5
4,AAACCCAAGACAAGCC,1,swap_crx3_to_ctaatccc_forward,Rod,AAACCTTACCCTTCCTTTACGCGG,CAATTTCGTCAG,1
...,...,...,...,...,...,...,...
8913183,TTTGTTGTCGTTCAGA,2,tail_conserve3_235_to_240,Rod,TCTGTATATTAGAGTTCCGGGCGG,GTATAACTATTT,1
8913184,TTTGTTGTCGTTCAGA,2,swap_crx4_to_ctaatccc_forward,Rod,TAAATGCGGGACAACACAATTTGT,GTTACAAGTATT,1
8913185,TTTGTTGTCGTTCAGA,2,swap_crx1_to_gggcttag_reverse,Rod,CGTCAACCAGCCCGTCGAATGTAC,TAAGTCCTTCGG,1
8913186,TTTGTTGTCGTTCAGA,2,ebox_gcagctgg_to_gcagcggg,Rod,AAATAGGAATCGGGGTCTGACTTG,TGAATTGGCCAG,1
8913187,TTTGTTGTCGTTCAGA,2,combo_Q50_crx5,Rod,TGCATATCGGAAAAGGGCTAGGGA,TTTATAATTGAT,1

In [38]:
to_dump_mpra.to_csv(f"{OUTPUT_ROOT}/read_wise_mpra_retina.tsv",index=False,sep="\t")

Now the u6 data.

In [40]:
to_dump_u6=final_u6.rename({"num_occurrences":"reads","cell_barcode":"cell_bc","name":"cre_id","leiden":"cell_type","replicate":"rep_id"},axis=1)
to_dump_u6

,reads,umi,pBC,rep_id,cell_bc,cell_type,cre_id
0,34,AAGGCGAGAGAG,ATGGAATG,1,AAACCCATCGCCGAGT,Rod,tail_conserve6_483_to_488
1,32,ACGCATCTCTTG,CGGTGAGA,1,AAACCCAGTAATCAGA,Rod,combo_Q50_crx4_crx2
2,32,ACTCTACCATAA,AATCTCCA,1,AAACCCAGTAATCAGA,Rod,ebox_gcagctgg_to_gcagctag
3,1,AGCCTCACAACC,ATGGAATG,1,AAACCCAGTAATCAGA,Rod,tail_conserve6_483_to_488
4,22,AGCCTCACAACG,ATGGAATG,1,AAACCCAGTAATCAGA,Rod,tail_conserve6_483_to_488
...,...,...,...,...,...,...,...
3640103,1,GCAACTCACCAT,CCTGAGTT,2,TTTGTTGAGCTGCCAC,Rod,combo_Mute_crx3_crx1
3640104,1,GTCTGAGGATCC,AGTGATTC,2,TTTGTTGAGCTGCCAC,Rod,tail_conserve4_428_to_433
3640105,26,GTGACTTTCTGT,CGCGTTAC,2,TTTGTTGAGCTGCCAC,Rod,combo_Q50_crx5_crx2
3640106,5,TTACAAGTCGCA,ATGGAATG,2,TTTGTTGAGCTGCCAC,Rod,tail_conserve6_483_to_488
3640107,2,TTGCCCGATACT,AGTGATTC,2,TTTGTTGAGCTGCCAC,Rod,tail_conserve4_428_to_433

In [42]:
to_dump_u6.to_csv(f"{OUTPUT_ROOT}/u6_rep_1.tsv",index=False,sep="\t")