Demo of `undo_one_hot_encoding` function

In [1]:
import scMPRAforge as scm
import pandas as pd
from formulaic import Formula

In [2]:
two=pd.DataFrame({'ct':['a','a','a','b','b','b']})
three=pd.DataFrame({'ct':['a','c','a','b','c','b']})

two_design=Formula('C(ct)').get_model_matrix(two,output='pandas')
three_design=Formula('C(ct)').get_model_matrix(three,output='pandas')

multi=pd.DataFrame({'ct':['a','a','a','b','b','b'],'foo':['1','2','3','1','2','3']})
multi_design=Formula('C(ct)+C(foo)').get_model_matrix(multi,output='pandas')
multi_no_intercept=Formula('C(ct)+C(foo)-1').get_model_matrix(multi,output='pandas')

In [3]:
two

  ct
0  a
1  a
2  a
3  b
4  b
5  b

In [4]:
two_design

   Intercept  C(ct)[T.b]
0        1.0           0
1        1.0           0
2        1.0           0
3        1.0           1
4        1.0           1
5        1.0           1

In [5]:
scm.undo_one_hot_encoding(two_design)

   Intercept         ct
0        1.0  reference
1        1.0  reference
2        1.0  reference
3        1.0        T.b
4        1.0        T.b
5        1.0        T.b

In [6]:
three

  ct
0  a
1  c
2  a
3  b
4  c
5  b

In [7]:
three_design

   Intercept  C(ct)[T.b]  C(ct)[T.c]
0        1.0           0           0
1        1.0           0           1
2        1.0           0           0
3        1.0           1           0
4        1.0           0           1
5        1.0           1           0

In [8]:
scm.undo_one_hot_encoding(three_design)

   Intercept         ct
0        1.0  reference
1        1.0        T.c
2        1.0  reference
3        1.0        T.b
4        1.0        T.c
5        1.0        T.b

In [9]:
multi

  ct foo
0  a   1
1  a   2
2  a   3
3  b   1
4  b   2
5  b   3

In [10]:
multi_design

   Intercept  C(ct)[T.b]  C(foo)[T.2]  C(foo)[T.3]
0        1.0           0            0            0
1        1.0           0            1            0
2        1.0           0            0            1
3        1.0           1            0            0
4        1.0           1            1            0
5        1.0           1            0            1

In [11]:
scm.undo_one_hot_encoding(multi_design)

   Intercept         ct        foo
0        1.0  reference  reference
1        1.0  reference        T.2
2        1.0  reference        T.3
3        1.0        T.b  reference
4        1.0        T.b        T.2
5        1.0        T.b        T.3