(notebook is incorrect & produces nothing! There is no DNA data we can use here, due to shallow sequencing. Keeping for posterity.)

In [3]:
import urllib.request
output_root="/gpfs/gibbs/pi/reilly/tabula_data/cohen"

In [4]:
#From https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5687474
urllib.request.urlretrieve("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5687474&format=file&file=GSM5687474%5Finput%5Flib%5Fexp%2Etsv%2Egz",
    "/tmp/c_dna.tsv.gz")

('/tmp/c_dna.tsv.gz', <http.client.HTTPMessage at 0x14da9e844f80>)

In [5]:
import pandas as pd

In [6]:
dna_counts=pd.read_csv("/tmp/c_dna.tsv.gz",sep="\t")

In [7]:
dna_counts

        counts           pBC                        rBC
0            4  CGCGTAAGATTC  GGTCACTCATTGCTGCAGTTGGAAG
1            5  TTAACGCGAATG  AACTCGACCTTCTCATTTGCGGGTT
2            1  CGAGGTTGTGGT  ATGTTATGCTGTTTTATAAGATGGA
3            1  GCGTAAGCAGTA  GTTGCCTGACACAGGTCCTAAGGAA
4            3  CTGGATTGCATA  GCAGTGGGTGGATTAAGTGGTTTGG
...        ...           ...                        ...
808697       1  GCAAGTACGATC  TGAGCAACATCGTCGAACTGTTGGT
808698       1  TGAGCGCGTGAA  AGTATTTACCGCCGACATATAAACC
808699       1  GCTTGGTCGCTT  CCGTACGAACACTTCATCACAGACT
808700       1  GGTTCGTTACTC  CATGATATTAGACACGTTATCCGGG
808701       1  AACGCAACCGAA  GAAGTTCGCGGTGCTTCAATTGGCT

[808702 rows x 3 columns]

In [10]:
DATA_ROOT="/home/mcn26/palmer_scratch/tabula_data/raw_recap/cohen_retina"

#excel was downloaded in step 09, break_by_barcode

CRE_IDs=pd.read_excel(f"{DATA_ROOT}/sup.xlsx",sheet_name="Supplementary Table 5",skiprows=1)
CRE_IDs.drop(["order_name","sequence"],axis=1,inplace=True)
CRE_IDs.rename({'barcode':'pBC','name':'cre_id'},axis=1,inplace=True)
assert len(CRE_IDs)==len(CRE_IDs["cre_id"].unique())==len(CRE_IDs["pBC"].unique())
CRE_IDs

                        cre_id       pBC
0    ebox_gcagctgg_to_acagctgg  AACAACAC
1    ebox_gcagctgg_to_ccagctgg  AACAAGGT
2    ebox_gcagctgg_to_tcagctgg  AACACTGA
3    ebox_gcagctgg_to_gaagctgg  AACATTCC
4    ebox_gcagctgg_to_ggagctgg  AACCAGCC
..                         ...       ...
110        combo_Q50_crx3_crx2  CGTAACAC
111        combo_Q50_crx3_crx1  CGTAGCTT
112        combo_Q50_crx2_crx1  CGTCTATG
113                       wt_1  CGTTCTCG
114                       wt_2  CTACCGGA

[115 rows x 2 columns]

In [13]:
pd.merge(CRE_IDs,dna_counts,how='left',validate='one_to_many',on='pBC')

                        cre_id       pBC  counts  rBC
0    ebox_gcagctgg_to_acagctgg  AACAACAC     NaN  NaN
1    ebox_gcagctgg_to_ccagctgg  AACAAGGT     NaN  NaN
2    ebox_gcagctgg_to_tcagctgg  AACACTGA     NaN  NaN
3    ebox_gcagctgg_to_gaagctgg  AACATTCC     NaN  NaN
4    ebox_gcagctgg_to_ggagctgg  AACCAGCC     NaN  NaN
..                         ...       ...     ...  ...
110        combo_Q50_crx3_crx2  CGTAACAC     NaN  NaN
111        combo_Q50_crx3_crx1  CGTAGCTT     NaN  NaN
112        combo_Q50_crx2_crx1  CGTCTATG     NaN  NaN
113                       wt_1  CGTTCTCG     NaN  NaN
114                       wt_2  CTACCGGA     NaN  NaN

[115 rows x 4 columns]

In [ ]:
#dna_counts.rename({'rBC'},inplace=True)