In [1]:
%load_ext autoreload
%autoreload 2
import scMPRAforge as scm

2025-08-19 12:40:42.318628: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-19 12:40:42.322857: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /vast/palmer/apps/avx2/software/code-server/4.91.1/lib:/vast/palmer/apps/avx2/software/gettext/0.22.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libiconv/1.17-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/ncurses/6.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/XZ/5.4.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/expat/2.6.2-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/cURL/8.7.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/OpenSSL/3/lib:/vast/palmer/apps/avx2/software/zlib/1.3.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/GCCcore/13.3.0/lib64
2025-08-19 12:40:42.322872: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
import pandas as pd

## Test wald test

In [3]:

#create dask cluster
from dask.distributed import Client, LocalCluster
cluster=LocalCluster(n_workers=10)
client = Client(cluster)

path="/gpfs/gibbs/pi/reilly/tabula_data/shendure"
name="ortho_primordial"

import os
if os.path.isdir(path+"/"+name):
    print("[+] Model found. Loading...")
    primordial=scm.ortho.load(client,path,name)
    shendure=primordial.training_data
    primordial.precompute_wald(client)
    # primordial.save(path, name) 
else:
    print("[+] Model not found. Creating...")

    #load data
    data_root="/gpfs/gibbs/pi/reilly/tabula_data"
    shendure=scm.scMPRA_data.from_tsv(f"{data_root}/shendure/shendure_counts_grouped.txt")
    
    shendure.set_negative_controls(["minP","noP"])
    shendure.set_reference_cell("Pluripotent")
    shendure.ortho_filter()

    primordial=scm.ortho()
    primordial.criss_cross(client=client,
                       dat=shendure)
    primordial.extract_params(client)
    primordial.precompute_wald(client)  
    primordial.save(path,name)

[+] Model found. Loading...

In [4]:

# Wald tests now hit the precomp cache automatically:
test_fn = scm.build_wald_test_fn(primordial, shendure, cre_mode="vs_reference")
runner  = scm.HypothesisTester(test_fn=test_fn, test_type_name="wald")

In [5]:
# by-cell-type: test many CREs in NeuroectodermBrain vs the 'reference' negative control
hs_ct = scm.make_by_celltype_hypotheses(
    comparison_cell_type="NeuroectodermBrain",
    counts=shendure,
    comparison_cres="all",          # or a list like ["CRE1","CRE2",...]
    reference_cre="reference",      # this is how you labeled minP/noP
    meta="emvar_screen"
)

# by-CRE: test CRE123 across all cell types vs the baseline cell type
hs_cre = scm.make_by_cre_hypotheses(
    comparison_cre="all",
    counts=shendure,
    comparison_cell_types="all",    # or a list
    reference_cell_type="reference",   # will default to counts.reference_cell_type if set
    meta="cell_specificity"
)

# all CREs within each cell type, vs the 'reference' negative control
hs_all_ct = scm.make_all_by_celltype_hypotheses(
    counts=shendure,
    reference_cre="reference",
    meta="emvar_screen",
)

# all cell types for each CRE, vs the dataset’s baseline cell type
hs_all_cre = scm.make_all_by_cre_hypotheses(
    counts=shendure,
    reference_cell_type="reference",  # will be normalized to 'reference'
    meta="cell_specificity",
)

In [6]:
hs_all_ct.to_dataframe()

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta
0,Bend5_chr4_8175,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
1,Cdk5r1_chr11_12559,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
2,Col1a1_chr11_15322,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
3,Col1a2_chr6_77,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
4,Igfbp4_chr11_16711,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
...,...,...,...,...,...
1446,Txndc12_chr4_7973,reference,reference,reference,emvar_screen
1447,Lama1_chr17_7787,reference,reference,reference,emvar_screen
1448,Epas1_chr17_10064,reference,reference,reference,emvar_screen
1449,Btg1_chr10_9578,reference,reference,reference,emvar_screen
1450,Igfbp4_chr11_16694,reference,reference,reference,emvar_screen

In [7]:
hs_all_cre.to_dataframe()

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta
0,Bend5_chr4_8168,NeuroectodermBrain,Bend5_chr4_8168,reference,cell_specificity
1,Bend5_chr4_8168,ExEndodermParietal,Bend5_chr4_8168,reference,cell_specificity
2,Bend5_chr4_8168,EpiblastPrimitiveStreak,Bend5_chr4_8168,reference,cell_specificity
3,Bend5_chr4_8168,SurfaceEctoderm,Bend5_chr4_8168,reference,cell_specificity
4,Bend5_chr4_8170,EpiblastPrimitiveStreak,Bend5_chr4_8170,reference,cell_specificity
...,...,...,...,...,...
1240,ubcP,NeuroectodermRostral,ubcP,reference,cell_specificity
1241,ubcP,ExEndodermParietal,ubcP,reference,cell_specificity
1242,ubcP,Haematoendothelial,ubcP,reference,cell_specificity
1243,ubcP,Cardiomyocytes,ubcP,reference,cell_specificity
1244,ubcP,ExEndodermVisceral,ubcP,reference,cell_specificity

In [8]:
primordial.wald_precomp

In [10]:
wald_by_cre = runner.run(hs_all_cre).to_dataframe()

KeyboardInterrupt:

In [13]:
wald_by_cre

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta,test_statistic,p_value,fold_change,flattened,test_type,bh_p
0,Bend5_chr4_8168,NeuroectodermBrain,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1,Bend5_chr4_8168,ExEndodermParietal,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
2,Bend5_chr4_8168,EpiblastPrimitiveStreak,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
3,Bend5_chr4_8168,SurfaceEctoderm,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
4,Bend5_chr4_8170,EpiblastPrimitiveStreak,Bend5_chr4_8170,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1240,ubcP,NeuroectodermRostral,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1241,ubcP,ExEndodermParietal,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1242,ubcP,Haematoendothelial,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1243,ubcP,Cardiomyocytes,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1244,ubcP,ExEndodermVisceral,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0

In [9]:
wald_by_ct  = runner.run(hs_all_ct).to_dataframe()

NameError: name 'find_treatment_index' is not defined

In [ ]:
wald_by_ct

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta,test_statistic,p_value,fold_change,flattened,test_type,bh_p
0,Bend5_chr4_8175,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,NaN,NaN,NaN,False,wald,1.0
1,Cdk5r1_chr11_12559,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,NaN,NaN,NaN,False,wald,1.0
2,Col1a1_chr11_15322,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,NaN,NaN,NaN,False,wald,1.0
3,Col1a2_chr6_77,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,NaN,NaN,NaN,False,wald,1.0
4,Igfbp4_chr11_16711,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,NaN,NaN,NaN,False,wald,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1446,Txndc12_chr4_7973,reference,reference,reference,emvar_screen,NaN,NaN,NaN,False,wald,1.0
1447,Lama1_chr17_7787,reference,reference,reference,emvar_screen,NaN,NaN,NaN,False,wald,1.0
1448,Epas1_chr17_10064,reference,reference,reference,emvar_screen,NaN,NaN,NaN,False,wald,1.0
1449,Btg1_chr10_9578,reference,reference,reference,emvar_screen,NaN,NaN,NaN,False,wald,1.0
1450,Igfbp4_chr11_16694,reference,reference,reference,emvar_screen,NaN,NaN,NaN,False,wald,1.0

In [13]:
some_ct = next(iter(primordial.by_cell_type.model.keys()))
Xnames = primordial.by_cell_type_design[some_ct].result()["nb_regressors"].columns.tolist()
print(Xnames[:10])

['Intercept', "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8168]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8170]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8172]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8174]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8175]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8179]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8192]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8199]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8201]"]

In [14]:
cluster.close()

2025-08-19 12:40:32,882 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:36993' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'lambda-532d0d01b625f57ae52cfe2f49679de6', 'lambda-f10b535da16a2a151714280ae3fefb66', 'lambda-7c8481f38b3032e121075e2fb91d844c', 'lambda-8861e79eb441911e1b82b2d2aa6119a3', 'lambda-dd52296b100e960ea76d8eeb4f76f73c', 'lambda-4a55c47f83c10d04d7c41ba0415e9d04', 'lambda-830504c375a36ea9c44503674fa21137', 'lambda-454aa038ef716d78d8d450f84a408b9b', 'lambda-dbdbe5e02b26871416e795b9f78bb63e', 'lambda-7b0a049a3c5f5d731404bc063c00fc7a', 'lambda-d7ecc73e205068488d52b8fbc05fecf8', 'lambda-b8c5024887c478be42d23ac425211fbf', 'lambda-a44157b3efc6b2abdd669d9135ddfb25', 'lambda-e411483872318e4a5829f9375bb9616c', 'lambda-775cf473419947618511c8e44db76060', 'lambda-bf9a100a69860aa7f556958e132d2262', 'lambda-78ed592bc0bf37ed366c1e347977c2df', 'lambda-fb59cad9b222952282eb0e299253df3c', 'lambda-08de87c0c6baf321cc4cada71d8b2a6f', 'lambda-6c837ec673887fc49e4b263d79c6be9c', 'lambda-6704f92eb76b25625de3519292d57a8f', 'lambda-c636c27b5b92923691cbb631eedce7c6', 'lambda-ab98ee70acfe1a9bc51f36565405faf1', 'lambda-662cef9b658a3dd6d288e097ff1a52b2', 'lambda-453d54b7bd43bec92deb11cc21a215c8', 'lambda-892bd2f08c6b9302250dc932f13345c4', 'lambda-1158798cf40d34a126bd446038bd1e3c', 'lambda-4ed865ddae5728f7589ca053a06720f9', 'lambda-baa9db7a061a4ae473d8778dd7773c67', 'lambda-23752445fb5d15e6c7ae84d62dd182ec', '_build_wald_precomp_for_subset-e53b2c0da18a70977ea01e82044860d6', 'lambda-0c8e6dfc453a417384452321db3950f8', 'lambda-56fac03f6b9f4d28ccac13ad441fc5cb', 'lambda-963a158305a4e0d368c7eeaae9b4d5a5', 'lambda-6df5d6d5a19b4987e8ef86b5ef19b908', 'lambda-59c6a382907319ef775cd7dcba6166a0', 'lambda-a942c0bd29317df06107ed7951504ab7', 'lambda-a057f830faaa80aac931ae90599b8827', 'lambda-04c98780ea89642520d2a9adafa55043', 'lambda-2cd48952ba88ed0645eca66c9069437f', 'lambda-cc192ad861a14d83230bcc0ee1062c1f', 'lambda-147fa6437cea4a1eace070646cc8b571', '_build_wald_precomp_for_subset-e3da2cb4850662c708dd5d060be48d35', 'lambda-c871735e827374291740151a2d920664', '_build_wald_precomp_for_subset-d7e321a04f2df4ab5dc3dde55fc8c7f0', 'lambda-269ded08a79da24307c6eb9725c34557', '_build_wald_precomp_for_subset-c2db8f899c5436f248a4bc5a86aa9b33', 'lambda-219d12c1f9cc78cfd46eafd5142e3c1c', 'lambda-f2d04477ba05dbb14908260904a3ec82', 'lambda-749ecbd3d8f30b454a4f0798b9adf615', 'lambda-88805700d30c4c119db78d244a941f0c', 'lambda-065cb5dfd938c6eb8a85a8dcc31ebeee', 'lambda-afc57b23f5f6111e4aee8972050be4d4', 'lambda-5402c16cddf52b09cb1b84571ea9cddc', 'lambda-cfb508042c79dd27afb3c0456e2e4720', 'lambda-1847a665fb9e246d9839308e2898e3ef', 'lambda-f668d13db17c20eb0fadd40a19a28f46', 'lambda-3370cc927bf08ddc23fe936ce931cf72', 'lambda-1027a27cf2a5e30bdc817253ec393475', 'lambda-f1de0e6c12ac66528d1800b8092a749e', 'lambda-2706790b9736d81c8f28fcf060007b12', 'lambda-cd7979b4d1d33cb13aac803bc9fcbf5b', 'lambda-e0a3565edb071d367e048d30516c0004', 'lambda-e1a0d69ccbef5d45334e21973e11b3a6', 'lambda-4bcd709447d0bc0ece9ab94d394b7721', 'lambda-56d682ab035624ce7c015d41043e1c33', 'lambda-632635dc66aa5a32dac3285d112f1212', 'lambda-28402cb4d926d26056958c8f7c39cff4', 'lambda-0a4a18bcc0b9a057826b0520eb099aed', 'lambda-6a534a09a852ad095254df4d1537d04a', 'lambda-dddb663a585c13fc02829f9c407c4434', 'lambda-fd14483bf461bdbdaeb05d43b0ea315e', 'lambda-14d53ecd2c54e3314e2d9d8643454e60', 'lambda-61146b680f4ac561bf7ddebb02cb85e5', 'lambda-e486d6e909faced6613edd87eaffcba4', 'lambda-ea1c1ffebfa496f8ba537d57bba46697', 'lambda-9c35d5f52c53f7e1a5394d9ca16275f6', 'lambda-7dde86f3c9f0a007c114afb57eb08a99', 'lambda-23fd0e284f3362e6ab14751172187a54', 'lambda-e3d77b2f97c0a30af85399ddbf73ab47', 'lambda-a7d1d653d63e53eb8c7ec998db22ec4f', 'lambda-7f73e0dd085a2b415f5091783f258f6a', 'lambda-358c87a2fca4996510db68d591112cde', 'lambda-3fbf2d64bffda23e23ecc1119405db50', 'lambda-39c79ccd249198031a641eaffb1e9248', 'lambda-a37db7f2043edb6f42317288aedf566a', 'lambda-1f92b06b7b1e52ab6baf2b3a192d89ee', '_build_wald_precomp_for_subset-9fb02737fe084ffe729bd75a99643124', 'lambda-771413b0c77336240f10a320109a9268', 'lambda-137318c6182400deeb2646375ff259ac', 'lambda-2fdbc2e2d7401f51f7b4a7866bbf9341', '_build_wald_precomp_for_subset-fc22151fc7bfda496ff8ffe608266464', 'lambda-6b68149ecc07c4e0260fee9d8ee08a95', 'lambda-ff65fa46bf93380296919e1af39128a2', '_build_wald_precomp_for_subset-e8d9e760283ad2fd76afb3a9364a0280', '_build_wald_precomp_for_subset-39e3b3f13669fe7a403a7b917e9911f2', 'lambda-f7dc858b3c63da9501b18174a5297ca6', 'lambda-9ba2bbe230ad121269e1658bda6116ca', 'lambda-a1e60a72221f47c88b6d361e001ed70c', 'lambda-c5ac44c02d8eaf7d1a52b62bed9e7b2d', 'lambda-16db403083fa292b39f3b080b07c122f', 'lambda-ac7d28f890166717b5128ba56b4ae7be', 'lambda-3e48ea2902003fc783c2812a51c0e83d', 'lambda-6c19e8bbb63f63e8927b059809d8da30', 'lambda-972428900aef4d8c36ff0d1a2ebbbc12', 'lambda-40c1f2d5274583dc36057837e3756f88', 'lambda-d05c65e0713758bd412a05a0088d7a94', 'lambda-54d83ee867c284b35642b30f607f3624', 'lambda-76ad3a7fe3b5c8e92459e63bb1f8115e', 'lambda-c513e081c687ad7797ae39ec7267f8b9', '_build_wald_precomp_for_subset-b6a44a3cbaba720ae969387608a4362f', 'lambda-af44c77b98d10f4ae424f9b374cfa742', 'lambda-f0cc921e165218c98acde7095827c46c', 'lambda-fb5e157da99a190dd8b0c743a4e4e3dd', 'lambda-ba9332d9fa99e6c8206f0cbb7f725ed1', '_build_wald_precomp_for_subset-ad90f88d10cd4cff5c7df47cc731c877', 'lambda-931b9f50a3430ec71e25609df986fc53', 'lambda-9310d040668fcbd1c719a57425f9014b', 'lambda-9042a0e629e39bc041c8b6e0b5b81526', 'lambda-c51a7f55266a213bd2dd9fe02c9b19f8', 'lambda-3afdc57b06c839016a66691eef40ff5d', 'lambda-3d9bbcd4aabfa6b946af6b07636ef257', 'lambda-baec462b13ac7d29b75df46f7bf7970f', 'lambda-1e5afce33a5e3c719f558ba1faa5007a', 'lambda-8971f405ad25a65f139a4b82c48c0d97', 'lambda-954d1740f6eb2d7cdb27a559347b83cf', 'lambda-31863092056cb4f506193fe9bd98cc14', 'lambda-7179e76b8c1693f1b1cb195c829d2395', 'lambda-712c8e04c0c50cb92d9f3a7038716389', 'lambda-512df3a0c76c6377b7b53ca68d0ddb59', 'lambda-ae5518bb9c01043215d14fa6c7c4680f', 'lambda-9408112a1731a64be1dc18dab8323966', 'lambda-ac936216c2ebd972302ee1e79891e514', 'lambda-d1509c4418a3cda7fb5b6333b129ece4', 'lambda-8b6476dbd1908e9c12acf07762bbae30', 'lambda-4a09c5654b4aa69ca9b32c7cdf836e87', 'lambda-27afea1bd8630b31b4973a5d45530189', 'lambda-a7856c78d4c704798fccdb8a42100238', 'lambda-9d230481994b3fcfed22ae13ba6b4377', 'lambda-30f37fdfb1cb23cb2cd8faaa88504049', 'lambda-170cc010714afc9234ea68b7ae038e8f', 'lambda-5de74cd0ccbbfef8db238a7a06ac7d06', 'lambda-190e1dba1473e7afd4007eff7c36c3bb', 'lambda-926fc2e043b462dcd711146a8ab4b65b', 'lambda-85956c5cdb87ad521ba887aa1c3a958d', 'lambda-45d0078bb49316e9ec6b4906203d98c3', 'lambda-e542ad34e5cfe656467eee16f3c2ffbf', 'lambda-9421a74ff3be5750e70cedbf33bec17c', 'lambda-3de6bbfde2439cb0aec5b7b3fb25ee43', 'lambda-ac172b5415ad6bd5e58be8752619f6a6', '_build_wald_precomp_for_subset-773fa58fc6280e2c69763e2f92b2d6bc', 'lambda-4fb7c3208f0e5576dad00087cb55c334', 'lambda-caba9b0889d586e5794d0b08357a2e2f', 'lambda-bdead4f90253bdaa6ce50089a4ef67e8', 'lambda-3c5c6626eb14a21aa4c71d87f98bde82', 'lambda-156a02b637e79a08463140fd4bd82d2f', 'lambda-da3712872258dd0758597e9529d8fbf7', 'lambda-644b5e4d7485c498ba94af5b0e50022c', 'lambda-8afdcc73902ad37e132c9fe7499c2468', 'lambda-0ecea111755ad405ad898e97879e3cc9', 'lambda-18f78b9919f556e8167151fce2238b8e', 'lambda-f55410740c4e81750d3dc84a75dfb0cd', 'lambda-389cfe10fb71f5ed7c0cc2ec998fa09e', 'lambda-44528eebcf8257fdaae492baae627137', 'lambda-ab3de4919f653c2f9676f04299761c08', 'lambda-3e36cfed150036e155259aa6495512c8', 'lambda-4310b554ed1e4162d2704cc8523d3cd0', 'lambda-3770d61f8a4486764426cb280685f279', 'lambda-71583bf7b491fa71ffe9077759b63ed9', 'lambda-417da2b203cd3e18f74d4778fde890ff', 'lambda-c8ae976026f982bc20a5b0d75ca5f9e9', 'lambda-1b3dd78155e8e75f84e1d1b53309ff7a', '_build_wald_precomp_for_subset-af207d978342933fcf33837dc7c9a6e0', 'lambda-6492c9d67cdb1406ae53cb842f048f0b', 'lambda-a145493613032d174e183b806635b267', 'lambda-0520f322588eebda987cdb32ae0bfb9e', '_build_wald_precomp_for_subset-60d25ef519afeed559ab0fab56070ffa', 'lambda-f7323f44134603ef86c93e8e7d02525a', '_build_wald_precomp_for_subset-47858398bf24e36770822f4acc379be3', 'lambda-8ecce278225f774801c385b534b6c39c', 'lambda-d41c1148f3137397ec98266bc838ec88', 'lambda-aa13150c665077cdc92a3f0a966ba57b', 'lambda-562308e7c4f32e81311f6ab2d620be48', 'lambda-72be91d8932945f7c7e9e5980bc7b2cb', 'lambda-c0f8c619de73672a96961479014b315d', 'lambda-9bf171152db0b834c5ec629f1f1b31bd', 'lambda-f8a8d9922b05a0c9f97656abfc2b042f', 'lambda-1c1c291f7d56764c4d87df8f1d5f8b8f', 'lambda-059d32992cf38eeedda8e39d7516c0fb', 'lambda-5a114d388231aad12411cd9718312b90', 'lambda-27d711ac588144ba8e36c10395274873', 'lambda-e9344ed71ab70f5f34a0cd337ab6d0ea', 'lambda-fb218cf3d23ee0aaeb23d0a0bf57a30a', 'lambda-64f2514d5bf656c2804815b561a3fd2d', 'lambda-d2e667a93f942ee28d39fe2f0c42eefc', 'lambda-e184a2585e41c5979b1cebe4ccaa0d71', 'lambda-1cc1ae39d784400c5aa9c3a5f7224b3e', 'lambda-c92682b970228e19027715ce058bcf86', '_build_wald_precomp_for_subset-4f9fdfa597150e4a3dff73e5ccefda5d', 'lambda-64690c991c53695c9aae92ac0c9400b1', 'lambda-b6658c3be886367d08a96838f16722b2', 'lambda-a2ee79556b3e59886e5f4f461be8303f', 'lambda-a412d29c606eec4e591abf63ce310857', '_build_wald_precomp_for_subset-35c71d03c2cef83f5d8cc2211917a354', 'lambda-2b9b012ff092bda6e1205dae8659d8a4', 'lambda-563f2ad903fcaae7935fbbdede8d3016', 'lambda-622c578747e6de9e9e1e8fb8380f3523', 'lambda-a35ce71ff37cc7189da2f676dbb2d493', 'lambda-8c56acdcfbfda8e33de7c9a90fd7bc65', 'lambda-7b393a836b0c9f777af150d5739ac75d', 'lambda-a9b29af051db2806c861372d502c07f7', 'lambda-33d9460a3685ebc7632a8e7f602ed5fb', 'lambda-464f0e8d22715b3cee2a44f88917c6d9', 'lambda-8ad269b865a4a70fffa98836e8806079', 'lambda-4089eb1dc7ea475e69a8b465ee415ae0', 'lambda-c38e905ddb40e0c4ff388cd28c6bd9d3', 'lambda-ba30e1a74cc74341c00f7505f5c8b72c', 'lambda-b31c7d465331bbb080d58a9ea3bc3f09', 'lambda-8e0001d013c0a76aef3715ab71529f91', 'lambda-a9afe4a2aa2cb6bf3cc31bcbc7b09c7f', 'lambda-31f2df8572f5b149db21b0a1e4fe5f5b', 'lambda-2f751e1e41b43011df7d395fa069d679', 'lambda-2fa1a86cfe7a74b4171d0d038e3fc4da', 'lambda-a31249cc0fa62a9a227509470fea12c9', 'lambda-1f4a713cf761c2e8a0ea6695f253db1d', 'lambda-33cc868cae117b30e47934b884f7c2f0', 'lambda-931716171bbc3e6c18ed2c89a2105c9e', 'lambda-fba2f87ec5a2751a21bd57c501c7fead', 'lambda-379d52fc15c74db4234dfd3e36fb7166', 'lambda-782a8b795dce68baafa21e11f1c6424f', 'lambda-1835cc9ecfc3d53fb42443c25724d396', 'lambda-1960b0bd440a79d2e370b942a58481ec', 'lambda-94530b1edb036fc957032a53c68c3368', 'lambda-28680c2d56f4b1bd2751c921b6441ae6', '_build_wald_precomp_for_subset-90688c74f3d6d3bbd146a28c071385de', '_build_wald_precomp_for_subset-36e1772c929b6708adf8a7b590017931', '_build_wald_precomp_for_subset-18f81af16b38e99458aff0f29e264327', 'lambda-2a64fa43fc3f86f7f2c91f0280508826', 'lambda-5425ef8ac15596700f0d1463e1940c36', 'lambda-f18774cb08eea78b9f9deea98dafed6c', 'lambda-5e104a550f9dc545998f1e392633b6b1', 'lambda-19f02554c9223898056ccc1d7fb29b1c', 'lambda-99c0f809f664d2ef70d57556b0583d21', 'lambda-1659e65971cc0d6b874001f9104b92af', '_build_wald_precomp_for_subset-33d7ff06f90ac7a6de0856787a25804e', '_build_wald_precomp_for_subset-c9362105ae3a6e4b8b240b9881e9795e', 'lambda-52c0db0650bb78c7dbe7e365c0b82831', 'lambda-9847e3a300ff4ae4fe76b89c98043932', 'lambda-3c2a5edf090cb57271cf52218acfb672', 'lambda-ef73f154a1ca2469fd98d3e058536197', '_build_wald_precomp_for_subset-6d2a20a52864f4e2ca7d73d788b5046c'} (stimulus_id='handle-worker-cleanup-1755621632.8813667')
2025-08-19 12:40:33,016 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:42013' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'lambda-3ae963e877049d02d448d340628885e0', 'lambda-6539aaf88b52e1e8d0d991a55f9b265d', '_build_wald_precomp_for_subset-bd383f6bbe139e1afd8ed94538f7d9be', '_build_wald_precomp_for_subset-7fad7d87c4c4d586d9c8d158ba290262', 'lambda-c05bd47fbb56bfc7511ec4e3153ad760', '_build_wald_precomp_for_subset-173688cb41fb91fab6c6f04c198d10d2', 'lambda-64a79c1ca8c3328e30f1065c2b746978', 'lambda-81120b34a588becdac03c6cd815738f0', 'lambda-681696850b826186ff33bbb18bcc557d', 'lambda-eee4a95988ea181e6932ebe6416c947e', 'lambda-a695c506914946fa14ed2ff9ec445a17', '_build_wald_precomp_for_subset-3774cf594a22be1b56402affbd9617f7', '_build_wald_precomp_for_subset-c65cf952706538cdfe4ca1d279a2311b', 'lambda-16b7402454ae3a3879126106990bf046', 'lambda-35152529d62b4fe4e2b40314b96c412b', '_build_wald_precomp_for_subset-4f2bbdd164a769ec8a766dd8ec802e29', 'lambda-771f4a1ccf45945b37026f24c9890a00', '_build_wald_precomp_for_subset-ff92bbaf4f0c5091fe1e30147126fa57', 'lambda-38080592a5eaf1c7f069e0d10df25516', 'lambda-43bda5068e4057dbd18f329949960acc', 'lambda-00fda8c6afca6884c3cb505db289578e', 'lambda-78ecff000b539821fe0780d68e1cb787', '_build_wald_precomp_for_subset-2514ab465dc6f7b7ef5327f978b5639a', '_build_wald_precomp_for_subset-55014f4dc1ecc59d9ebfe620d428cd7a', 'lambda-099fe6ffe822839ca1bd3927a2848aee', '_build_wald_precomp_for_subset-d2a800ed77b7ccb17641dccc16cf05e0', '_build_wald_precomp_for_subset-6359904524f9bb4f5f783185cbcb131b', 'lambda-6ba956b4fa79dd99690b48edd69afbca', '_build_wald_precomp_for_subset-298e90674ee322c3c8dee7b00959d5e3', '_build_wald_precomp_for_subset-e8a6c454e9e45f3eed18f319f9a94dec', '_build_wald_precomp_for_subset-980f1422f21d7cb2d7333dd2e53e7aa9', 'lambda-40ddb3d09796cf103cc382631ca7b92f', 'lambda-def1c4529fc17e8649fafea319593d3f', '_build_wald_precomp_for_subset-ba3f832f1d5539fa0657f0f3fcb3f3bd', 'lambda-7003b1156d69461fc4e44a4e30183949', 'lambda-afb99988cf83c6b593e5ac19cdcbe66c', '_build_wald_precomp_for_subset-ea71d6179959400fb0d94de87c208491', 'lambda-f75d10dac2354438c406e7e742bef84e', 'lambda-25aea2585623f01ed03fedd6fb1ca191', 'lambda-b7409919c73dadb8e331ad992fe58aff', 'lambda-f31b74855cf36661188e4d75b274101b', 'lambda-acb4ae941b673efa57cc2efabddc79e3', 'lambda-a0737fb3d94030623179ebb5d0456908', 'lambda-0d26b8cb186f6dcd79bafc534ddc23f0', 'lambda-d08217e8ec21db4480f1ec55e53c7cf3', 'lambda-8e6f8119402441bc3947ce7df85bdef5', 'lambda-49f0c9665b6248d0dece2078c9b500df', '_build_wald_precomp_for_subset-6c0046455b69b09e71ce174f96581aa8', '_build_wald_precomp_for_subset-e78a5be96c561bf23a84837db19fa184', 'lambda-eef9a8ab520f90bdb1e68bb9cb71b9c6', 'lambda-3ca2ddb08321919c45ee59b20fd0a190', 'lambda-57ca691235d22712720f1680669cba94', 'lambda-5aad8ef1939b655391c9d3adc3e9b425', 'lambda-3bf6cbf656c96286bbe567093fcc181c', 'lambda-6163117ed7a3e9e53a35394c8edffb05', 'lambda-3101424f450193cb47f2a49d309b8d1f', 'lambda-3fdaba998c87737416cb779468dd3baf', 'lambda-9befb5fdbaf7bd88332fb850fda313d8', 'lambda-d96bd7fbac63bb0d79de8a0dfd31cdcf', 'lambda-170991d57450988149f860e8af55aa88', 'lambda-ee2b75fe00b6ad870522c1aae04fea67', 'lambda-544f3634429b896e2dd75099bfd7ea44', 'lambda-96c22a556a473205cbfd73e980ef6e5b', '_build_wald_precomp_for_subset-4c659306b8e2d91edb804392c0cba6d0', 'lambda-1cdaf2d3371b9205eeee6085d99cc34f', 'lambda-ecf9ea2c5c171301fb1ad28afb98836d', '_build_wald_precomp_for_subset-e82bd8423aa5d4a97237ae710bb72817', 'lambda-2301530afd5d22312a79276d94f35b05'} (stimulus_id='handle-worker-cleanup-1755621633.0159645')
2025-08-19 12:40:33,019 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:42375' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'_build_wald_precomp_for_subset-6e0eaaddc19637c7aadd220fcc281462', 'lambda-19b279aec106afaa2a855fae59f39dca', 'lambda-7389a9080a5a33615cc7117eb685762b', '_build_wald_precomp_for_subset-f72e8c2fada8c323546f240329221b2e', 'lambda-bd1e92321b7de82622dc27fb1e221698', 'lambda-6ab998e0f424c2955cbf567aaaa23717', 'lambda-94580397d6c1d5d1863eff82e7a5b160', '_build_wald_precomp_for_subset-a126fa9962d5e3e0e0f78c11cf595343', 'lambda-c195b10060278ef4c92f824c4154f166', '_build_wald_precomp_for_subset-325d7f3f01cbaae0a75f8d8171fda5ba', '_build_wald_precomp_for_subset-053fb471204e786fb3e3195cd5a659ec', '_build_wald_precomp_for_subset-282b59cdede0a7ec177cbb7104ba041d', '_build_wald_precomp_for_subset-ec6bd6933d4b453d278f75c4c556446a', '_build_wald_precomp_for_subset-eef10ecb4a03be9759be4eb2159b0426', 'lambda-181c4190e0ff6a43148bcd050d55be5f', '_build_wald_precomp_for_subset-d0c0a28d59a153d7867789317917cdac', 'lambda-7b15237e470cc99fac27c2d4a8ce502c', 'lambda-550fe6e4bdee26b5cd6ccb7ce83fc1ce', '_build_wald_precomp_for_subset-90b0ec883a9f1b7a888736ef3c69fdc8', 'lambda-1f08ffb89abd2b34ac96af153ee7e2cd', '_build_wald_precomp_for_subset-b68d5a18fdad0f329854661f5567887e', 'lambda-ba04641908697f2c7ab0543e9434304f', 'lambda-389b294591429b38a48df089ae268b27', '_build_wald_precomp_for_subset-bb7e9e5a4567a061fa2838558392532a', '_build_wald_precomp_for_subset-926b748f6b1061c282d4e0479b505f0c', 'lambda-31b5a4c0b5e8e77beca4f95fd403f606', 'lambda-ff00dea2546f88cc5646386da7da2415', '_build_wald_precomp_for_subset-7d0c3bae6a7e394fa0799a45fe1ba277', 'lambda-c35116438526d97d1bce421bb9bc5912', 'lambda-3cf3ab611ae46ce326f1b4ba9e5e0c60', 'lambda-5d15aed30a68ab74f3aeba31e3662321', 'lambda-60ec53b7df75f30e1685462d2634bc66', '_build_wald_precomp_for_subset-cc0b3d48cceb43b46f3ffba48236036c', 'lambda-050f2749610310f5d81ded9c6f37984e', 'lambda-5ce59ad8b4143509b725a3c0ed74cbd7', '_build_wald_precomp_for_subset-5ddd5a0f1285b919549af8ca1676ba88', 'lambda-7b625ecf1fcb746f3558eafbc73553d5', '_build_wald_precomp_for_subset-6c4a4ba5d222fa4e3cb1f1a34b0dc8c2', 'lambda-a7efaceb2c9ee3eba50d8dba5e780d02', 'lambda-4b8009dfcd8b45ef1d2e9aefce48d5d1', 'lambda-542afcb978b58ab290265e8a642ebdaf', 'lambda-03b59b47174c4ea580aa9358149d8938', 'lambda-a33b60f60386f3990c65a509651d1524', '_build_wald_precomp_for_subset-812db076f34e90a7c7ad9d7ab80bf0a4', 'lambda-789eaba30400aca80ab33f267c1f2003', 'lambda-5cb5798709647976470dcf4c0eb0ea0a', 'lambda-d002116694754dbea376c6f8a68c0a85', 'lambda-8dc74e14542832d8c183f3c7b1a4b323', '_build_wald_precomp_for_subset-3b43c7209af08eacfb869a202aa07141', '_build_wald_precomp_for_subset-48d3eec93c7e015e13793d62762d6a2c', 'lambda-8763a930aec45b6bf32208b3bdf17db1', 'lambda-1a73a06342da8120fbcf66643de3b309', 'lambda-a75dda2ced2cd43e77c3a21be0399860', 'lambda-99283ecce71f02ca01f858b6c97a1e5e', '_build_wald_precomp_for_subset-c4e8297aaa4371954b3ef13592c428bb', 'lambda-8c19bb30b818b7222c2778f36d134e42', 'lambda-3a929fa49ff0831e2a56b8a02144ef51', 'lambda-94d6caa642c2705e93091046d14f6d6d', 'lambda-bf83062c8417932ed9c04eaea0349015', 'lambda-14bb83aee827228c43b6bcf8a3535272', '_build_wald_precomp_for_subset-0f57d74bdfa3f58f66cd65f2f9c4335c', 'lambda-a76c9eb00caa35de99d6d6fc0a950a97', 'lambda-f8efb5b5b805c953a097aeada290b68c', 'lambda-4f040b41a362c58e91191b272fbe2810', 'lambda-6087462892858b08fe08bfd6a18c0433', 'lambda-a39dbca28202e7bfa25aa9805dbfcbf6', '_build_wald_precomp_for_subset-a048e9fcee9f754e6c35260160ca8379', '_build_wald_precomp_for_subset-2a348c9207b0d6342cb005541e0e19a5', 'lambda-41bb0641be88c34feb112be9f6d5b012', 'lambda-23a6ab121f001ae520f4b82e5f0cd0a1', 'lambda-aa0b1982f9f98ab89a0cb3768c1c32cd', 'lambda-bab324dfd61ba465c4fcee5a89b81442'} (stimulus_id='handle-worker-cleanup-1755621633.01882')