A better version of `power_shendure_vs_minp.ipynb` with a more representative distribution of positive and negative effects. Specifically, we will be using the real values, plus many negatives.

Based on UKBB paper, expect ~30% of library to be active. So we will add 2x original size of negatives... 

We will also reduce computational burden by producing half-orthos.

# Imports & dask cluster creation

In [1]:
import scMPRAforge as scm
from dask_jobqueue import SLURMCluster
from dask.distributed import Client, LocalCluster
from pathlib import Path

%load_ext autoreload
%autoreload 2

2026-01-23 15:38:05.432837: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-23 15:38:05.435859: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/software/2024a/software/code-server/4.103.0/lib:/apps/software/2024a/software/gettext/0.22.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libiconv/1.17-GCCcore-13.3.0/lib:/apps/software/2024a/software/ncurses/6.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/apps/software/2024a/software/XZ/5.4.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/expat/2.6.2-GCCcore-13.3.0/lib:/apps/software/2024a/software/cURL/8.7.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/OpenSSL/3/lib64:/apps/software/2024a/software/zlib/1.3.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/GCCcore/13.3.0/lib64
2026-01-23 15:38:05.435868: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
local=True
if local:
    cluster=LocalCluster(memory_limit='48G')
    client=Client(cluster)
else:
    cluster=SLURMCluster(
        cores=2,#cores per slurm job
        memory="32G",#memory per slurm job
        processes=1,#dask workers per slurm jobTrueT
        job_extra_directives=["-p day", 
            f"--job-name=simclust_worker",
            f"--time=4:00:00",
            f"--output=worker_%j.out"]
    )
    cluster.scale(jobs=2)
    client = Client(cluster,
            timeout=f"{5*60}s",   # Client <-> scheduler timeout 
            heartbeat_interval="20s"  # Worker heartbeat interval
        )

In [3]:
client.dashboard_link

'http://127.0.0.1:8787/status'

# Ground truth creation

We will use parameter estimates from by_cell_type models as we expect these to be the most accurate.

In [4]:
data_root=Path("/nfs/roberts/project/pi_skr2/shared/tabula_data")

In [5]:
primordial=scm.ortho.load(client,data_root/"shendure","ortho_primordial_v4")

In [6]:
primordial.compute_model_qc()

In [7]:
import pandas as pd

In [8]:
vals=[]
for key in primordial.by_cell_qc.keys():
    working=primordial.by_cell_qc[key]['dat'].reset_index().drop(columns=["mean(umis_mpra_bc)"])
    working["cell_type"]=key
    vals.append(working)
vals=pd.concat(vals)
vals=vals.groupby(["cre_id","cell_type"]).mean().reset_index()
vals

               cre_id                cell_type         mu
0     Bend5_chr4_8168  EpiblastPrimitiveStreak    0.02805
1     Bend5_chr4_8168       ExEndodermParietal   0.034062
2     Bend5_chr4_8168       NeuroectodermBrain   0.019509
3     Bend5_chr4_8168          SurfaceEctoderm   0.019097
4     Bend5_chr4_8168                reference   0.046651
...               ...                      ...        ...
1457             ubcP                 Mesoderm  11.870977
1458             ubcP       NeuroectodermBrain  11.051645
1459             ubcP     NeuroectodermRostral   10.44203
1460             ubcP          SurfaceEctoderm  14.532331
1461             ubcP                reference  38.759719

[1462 rows x 3 columns]

In [9]:
vals.dtypes

cre_id                     object
cell_type                  object
mu           Sparse[float64, 1.0]
dtype: object

In [10]:
vals["mu"] = vals["mu"].astype(float)

In [11]:
vals.dtypes

cre_id        object
cell_type     object
mu           float64
dtype: object

Now that we have reasonable mu estimates for the real CRE, let us add 200% "indistinguishable from minP".

In [12]:
#make "corresponding" inactive CREs...
mapping = {
    val: f"inactive_{i}"
    for i, val in enumerate(vals["cre_id"].unique())
}
mapping

{'Bend5_chr4_8168': 'inactive_0',
 'Bend5_chr4_8170': 'inactive_1',
 'Bend5_chr4_8172': 'inactive_2',
 'Bend5_chr4_8174': 'inactive_3',
 'Bend5_chr4_8175': 'inactive_4',
 'Bend5_chr4_8179': 'inactive_5',
 'Bend5_chr4_8192': 'inactive_6',
 'Bend5_chr4_8199': 'inactive_7',
 'Bend5_chr4_8201': 'inactive_8',
 'Btg1_chr10_9572': 'inactive_9',
 'Btg1_chr10_9578': 'inactive_10',
 'Btg1_chr10_9588': 'inactive_11',
 'Btg1_chr10_9593': 'inactive_12',
 'Btg1_chr10_9612': 'inactive_13',
 'Btg1_chr10_9613': 'inactive_14',
 'Cdk5r1_chr11_12559': 'inactive_15',
 'Cdk5r1_chr11_12562': 'inactive_16',
 'Cdk5r1_chr11_12574': 'inactive_17',
 'Cdk5r1_chr11_12575': 'inactive_18',
 'Cdk5r1_chr11_12582': 'inactive_19',
 'Cdk5r1_chr11_12590': 'inactive_20',
 'Cdk5r1_chr11_12595': 'inactive_21',
 'Cited2_chr10_1239': 'inactive_22',
 'Cited2_chr10_1246': 'inactive_23',
 'Cited2_chr10_1248': 'inactive_24',
 'Cited2_chr10_1253': 'inactive_25',
 'Cited2_chr10_1254': 'inactive_26',
 'Cited2_chr10_1267': 'inactive_27',
 'Cited2_chr10_1270': 'inactive_28',
 'Col1a1_chr11_15258': 'inactive_29',
 'Col1a1_chr11_15259': 'inactive_30',
 'Col1a1_chr11_15269': 'inactive_31',
 'Col1a1_chr11_15270': 'inactive_32',
 'Col1a1_chr11_15273': 'inactive_33',
 'Col1a1_chr11_15275': 'inactive_34',
 'Col1a1_chr11_15276': 'inactive_35',
 'Col1a1_chr11_15301': 'inactive_36',
 'Col1a1_chr11_15307': 'inactive_37',
 'Col1a1_chr11_15316': 'inactive_38',
 'Col1a1_chr11_15322': 'inactive_39',
 'Col1a2_chr6_72': 'inactive_40',
 'Col1a2_chr6_73': 'inactive_41',
 'Col1a2_chr6_77': 'inactive_42',
 'Col1a2_chr6_88': 'inactive_43',
 'Col1a2_chr6_93': 'inactive_44',
 'Col5a1_chr2_2558': 'inactive_45',
 'Col5a1_chr2_2562': 'inactive_46',
 'Col5a1_chr2_2565': 'inactive_47',
 'Col5a1_chr2_2571': 'inactive_48',
 'Col5a1_chr2_2575': 'inactive_49',
 'Col5a1_chr2_2576': 'inactive_50',
 'Col5a1_chr2_2586': 'inactive_51',
 'Epas1_chr17_10056': 'inactive_52',
 'Epas1_chr17_10057': 'inactive_53',
 'Epas1_chr17_10061': 'inactive_54',
 'Epas1_chr17_10063': 'inactive_55',
 'Epas1_chr17_10064': 'inactive_56',
 'Epas1_chr17_10066': 'inactive_57',
 'Epas1_chr17_10070': 'inactive_58',
 'Epas1_chr17_10071': 'inactive_59',
 'Epas1_chr17_10116': 'inactive_60',
 'Foxa2_chr2_13806': 'inactive_61',
 'Foxa2_chr2_13808': 'inactive_62',
 'Foxa2_chr2_13812': 'inactive_63',
 'Foxa2_chr2_13818': 'inactive_64',
 'Foxa2_chr2_13820': 'inactive_65',
 'Foxa2_chr2_13830': 'inactive_66',
 'Foxa2_chr2_13835': 'inactive_67',
 'Foxa2_chr2_13840': 'inactive_68',
 'Foxa2_chr2_13841': 'inactive_69',
 'Foxa2_chr2_13856': 'inactive_70',
 'Foxa2_chr2_13858': 'inactive_71',
 'Foxa2_chr2_13861': 'inactive_72',
 'Foxa2_chr2_13862': 'inactive_73',
 'Gata4_chr14_5677': 'inactive_74',
 'Gata4_chr14_5693': 'inactive_75',
 'Gata4_chr14_5710': 'inactive_76',
 'Gata4_chr14_5714': 'inactive_77',
 'Gata4_chr14_5729': 'inactive_78',
 'Gata4_chr14_5742': 'inactive_79',
 'Gata4_chr14_5749': 'inactive_80',
 'Gata4_chr14_5752': 'inactive_81',
 'Gata4_chr14_5760': 'inactive_82',
 'Gata4_chr14_5762': 'inactive_83',
 'Gata4_chr14_5763': 'inactive_84',
 'Gata4_chr14_5776': 'inactive_85',
 'Gata4_chr14_5779': 'inactive_86',
 'Igfbp4_chr11_16694': 'inactive_87',
 'Igfbp4_chr11_16710': 'inactive_88',
 'Igfbp4_chr11_16711': 'inactive_89',
 'Igfbp4_chr11_16716': 'inactive_90',
 'Igfbp4_chr11_16728': 'inactive_91',
 'Igfbp4_chr11_16735': 'inactive_92',
 'Igfbp4_chr11_16738': 'inactive_93',
 'Igfbp4_chr11_16740': 'inactive_94',
 'Igfbp4_chr11_16743': 'inactive_95',
 'Igfbp4_chr11_16784': 'inactive_96',
 'Klf4_chr4_3934': 'inactive_97',
 'Klf4_chr4_3936': 'inactive_98',
 'Klf4_chr4_3946': 'inactive_99',
 'Klf4_chr4_3948': 'inactive_100',
 'Klf4_chr4_3949': 'inactive_101',
 'Klf4_chr4_3951': 'inactive_102',
 'Klf4_chr4_3952': 'inactive_103',
 'Klf4_chr4_3958': 'inactive_104',
 'Lama1_chr17_7784': 'inactive_105',
 'Lama1_chr17_7787': 'inactive_106',
 'Lama1_chr17_7788': 'inactive_107',
 'Lama1_chr17_7791': 'inactive_108',
 'Lama1_chr17_7793': 'inactive_109',
 'Lama1_chr17_7799': 'inactive_110',
 'Lama1_chr17_7814': 'inactive_111',
 'Lama1_chr17_7874': 'inactive_112',
 'Lama1_chr17_7892': 'inactive_113',
 'Lama1_chr17_7907': 'inactive_114',
 'Lamb1_chr12_2182': 'inactive_115',
 'Lamb1_chr12_2183': 'inactive_116',
 'Lamb1_chr12_2186': 'inactive_117',
 'Lamb1_chr12_2189': 'inactive_118',
 'Lamb1_chr12_2196': 'inactive_119',
 'Lamb1_chr12_2203': 'inactive_120',
 'Lamb1_chr12_2206': 'inactive_121',
 'Lamb1_chr12_2207': 'inactive_122',
 'Lamb1_chr12_2210': 'inactive_123',
 'Lamb1_chr12_2215': 'inactive_124',
 'Lamb1_chr12_2216': 'inactive_125',
 'Lamb1_chr12_2238': 'inactive_126',
 'Lamb1_chr12_2239': 'inactive_127',
 'Lamb1_chr12_2288': 'inactive_128',
 'Lamb1_chr12_2289': 'inactive_129',
 'Lamb1_chr12_2296': 'inactive_130',
 'Lamc1_chr1_12127': 'inactive_131',
 'Lamc1_chr1_12152': 'inactive_132',
 'Lamc1_chr1_12175': 'inactive_133',
 'Lamc1_chr1_12183': 'inactive_134',
 'Lamc1_chr1_12185': 'inactive_135',
 'Lamc1_chr1_12188': 'inactive_136',
 'Lamc1_chr1_12189': 'inactive_137',
 'Lamc1_chr1_12193': 'inactive_138',
 'Lamc1_chr1_12201': 'inactive_139',
 'Map1b_chr13_9429': 'inactive_140',
 'Map1b_chr13_9436': 'inactive_141',
 'Map1b_chr13_9445': 'inactive_142',
 'Map1b_chr13_9447': 'inactive_143',
 'Sox17_chr1_58': 'inactive_144',
 'Sox17_chr1_59': 'inactive_145',
 'Sox17_chr1_60': 'inactive_146',
 'Sox17_chr1_65': 'inactive_147',
 'Sox17_chr1_67': 'inactive_148',
 'Sox17_chr1_68': 'inactive_149',
 'Sox17_chr1_69': 'inactive_150',
 'Sox17_chr1_73': 'inactive_151',
 'Sox17_chr1_77': 'inactive_152',
 'Sox17_chr1_78': 'inactive_153',
 'Sox17_chr1_82': 'inactive_154',
 'Sox17_chr1_83': 'inactive_155',
 'Sox2_chr3_2005': 'inactive_156',
 'Sox2_chr3_2007': 'inactive_157',
 'Sox2_chr3_2008': 'inactive_158',
 'Sox2_chr3_2009': 'inactive_159',
 'Sox4_chr13_2052': 'inactive_160',
 'Sox4_chr13_2054': 'inactive_161',
 'Sox4_chr13_2055': 'inactive_162',
 'Sox4_chr13_2057': 'inactive_163',
 'Sparc_chr11_7180': 'inactive_164',
 'Sparc_chr11_7182': 'inactive_165',
 'Sparc_chr11_7195': 'inactive_166',
 'Sparc_chr11_7198': 'inactive_167',
 'Sparc_chr11_7199': 'inactive_168',
 'Sparc_chr11_7203': 'inactive_169',
 'Sparc_chr11_7205': 'inactive_170',
 'Sparc_chr11_7207': 'inactive_171',
 'Sparc_chr11_7210': 'inactive_172',
 'Sparc_chr11_7211': 'inactive_173',
 'Sparc_chr11_7213': 'inactive_174',
 'Sparc_chr11_7230': 'inactive_175',
 'Sparc_chr11_7233': 'inactive_176',
 'Sparc_chr11_7234': 'inactive_177',
 'Sparc_chr11_7235': 'inactive_178',
 'Sparc_chr11_7243': 'inactive_179',
 'Tgfbi_chr13_5692': 'inactive_180',
 'Tgfbi_chr13_5701': 'inactive_181',
 'Tgfbi_chr13_5705': 'inactive_182',
 'Tgfbi_chr13_5711': 'inactive_183',
 'Tgfbi_chr13_5724': 'inactive_184',
 'Tgfbi_chr13_5735': 'inactive_185',
 'Tgfbi_chr13_5741': 'inactive_186',
 'Tubb2b_chr13_2557': 'inactive_187',
 'Tubb2b_chr13_2568': 'inactive_188',
 'Tubb2b_chr13_2572': 'inactive_189',
 'Tubb2b_chr13_2576': 'inactive_190',
 'Tubb2b_chr13_2577': 'inactive_191',
 'Tubb2b_chr13_2578': 'inactive_192',
 'Tubb2b_chr13_2580': 'inactive_193',
 'Tubb2b_chr13_2583': 'inactive_194',
 'Tubb2b_chr13_2590': 'inactive_195',
 'Txndc12_chr4_7951': 'inactive_196',
 'Txndc12_chr4_7961': 'inactive_197',
 'Txndc12_chr4_7962': 'inactive_198',
 'Txndc12_chr4_7969': 'inactive_199',
 'Txndc12_chr4_7971': 'inactive_200',
 'Txndc12_chr4_7973': 'inactive_201',
 'Txndc12_chr4_7975': 'inactive_202',
 'Txndc12_chr4_7978': 'inactive_203',
 'eef1aP': 'inactive_204',
 'pgk1P': 'inactive_205',
 'reference': 'inactive_206',
 'ubcP': 'inactive_207'}

In [13]:
minP=scm.SHENDURE_BOUNDS.reference_activity
inactive=vals.copy().drop(columns=["mu"])
inactive["cre_id"] = inactive["cre_id"].map(mapping)
inactive["mu"]=minP
inactive

            cre_id                cell_type        mu
0       inactive_0  EpiblastPrimitiveStreak  0.019311
1       inactive_0       ExEndodermParietal  0.019311
2       inactive_0       NeuroectodermBrain  0.019311
3       inactive_0          SurfaceEctoderm  0.019311
4       inactive_0                reference  0.019311
...            ...                      ...       ...
1457  inactive_207                 Mesoderm  0.019311
1458  inactive_207       NeuroectodermBrain  0.019311
1459  inactive_207     NeuroectodermRostral  0.019311
1460  inactive_207          SurfaceEctoderm  0.019311
1461  inactive_207                reference  0.019311

[1462 rows x 3 columns]

This is 100%. Let us double to 200%...

In [14]:
# duplicated version with _b appended
inactive_b = inactive.copy()
inactive_b["cre_id"] = inactive_b["cre_id"] + "_b"

# stack them
inactive_double = pd.concat([inactive, inactive_b], ignore_index=True)
inactive_double

              cre_id                cell_type        mu
0         inactive_0  EpiblastPrimitiveStreak  0.019311
1         inactive_0       ExEndodermParietal  0.019311
2         inactive_0       NeuroectodermBrain  0.019311
3         inactive_0          SurfaceEctoderm  0.019311
4         inactive_0                reference  0.019311
...              ...                      ...       ...
2919  inactive_207_b                 Mesoderm  0.019311
2920  inactive_207_b       NeuroectodermBrain  0.019311
2921  inactive_207_b     NeuroectodermRostral  0.019311
2922  inactive_207_b          SurfaceEctoderm  0.019311
2923  inactive_207_b                reference  0.019311

[2924 rows x 3 columns]

Then stack with original gt...

In [15]:
final_gt=pd.concat([vals,inactive_double],ignore_index=True).rename({"mu":"true_mean"},axis=1)
final_gt

               cre_id                cell_type  true_mean
0     Bend5_chr4_8168  EpiblastPrimitiveStreak   0.028050
1     Bend5_chr4_8168       ExEndodermParietal   0.034062
2     Bend5_chr4_8168       NeuroectodermBrain   0.019509
3     Bend5_chr4_8168          SurfaceEctoderm   0.019097
4     Bend5_chr4_8168                reference   0.046651
...               ...                      ...        ...
4381   inactive_207_b                 Mesoderm   0.019311
4382   inactive_207_b       NeuroectodermBrain   0.019311
4383   inactive_207_b     NeuroectodermRostral   0.019311
4384   inactive_207_b          SurfaceEctoderm   0.019311
4385   inactive_207_b                reference   0.019311

[4386 rows x 3 columns]

In [16]:
assert len(final_gt[["cre_id","cell_type"]].drop_duplicates()) == len(final_gt)

# Creating artificial libraries

In [17]:
libraries=[scm.simulate_library(CREs=final_gt["cre_id"],
                 library_model=scm.SHENDURE_BOUNDS.library_model)
                 for i in range(5)]

In [18]:
libraries[2]

                cre_id               mpra_bc     abundance
0      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAA  1.562188e-05
1      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAC  1.377567e-05
2      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAG  6.199831e-06
3      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAT  1.358808e-05
4      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAACA  3.538427e-06
...                ...                   ...           ...
83872   inactive_207_b  AAAAAAAAAAACCACTGGAA  4.625026e-07
83873   inactive_207_b  AAAAAAAAAAACCACTGGAC  2.230791e-05
83874   inactive_207_b  AAAAAAAAAAACCACTGGAG  1.470057e-05
83875   inactive_207_b  AAAAAAAAAAACCACTGGAT  4.463305e-06
83876   inactive_207_b  AAAAAAAAAAACCACTGGCA  8.023394e-06

[83877 rows x 3 columns]

In [19]:
final_gt.dtypes

cre_id        object
cell_type     object
true_mean    float64
dtype: object

# Creating sim

In [20]:
sim=scm.de_novo_simulation(location=data_root,
                            name="twothird_pow_sim_2026-01-23",
                            client=client,
                            libraries=libraries,
                            library_mapping="corresponding",
                            n_sims=5,
                            experiment_bounds=scm.SHENDURE_BOUNDS,
                            ground_truth=final_gt)

scMPRAforge: INFO: No 'state.parquet' found for 'twothird_pow_sim_2026-01-23'. Initalizing new object.

In [21]:
sim.gamut()

In [22]:
#sim.save()

In [23]:
#sim

Make the hypotheses...

In [24]:
#spread_hypothesis.to_tsv(f"{data_root}/pow_sim_2026-01-03_hypo.tsv")
#hs_all_cre = scm.make_all_by_cre_hypotheses(
#    counts=demo_counts,
#    reference_cell_type="reference",
#)

In [25]:
sim.ground_truth.dtypes

cre_id       string[python]
cell_type    string[python]
true_mean           float64
dtype: object

In [26]:
#client.close()
#cluster.close()

scMPRAforge: INFO: A: drawn_library cols: Index(['cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type     object
cell_bc       object
cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: A: drawn_library cols: Index(['cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type     object
cell_bc       object
cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
dtype: object
scMPRAforge: INFO: C.5: cells_df cols: Index(['cre_id', 'cell_type', 'true_mean'], dtype='object'), types: cre_id       string[python]
cell_type    string[python]
true_mean           float64
dtype: object
scMPRAforge: INFO: A: drawn_library cols: Index(['cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type     object
cell_bc       object
cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
dtype: object
scMPRAforge: INFO: C.5: cells_df cols: Index(['cre_id', 'cell_type', 'true_mean'], dtype='object'), types: cre_id       string[python]
cell_type    string[python]
true_mean           float64
dtype: object
scMPRAforge: INFO: A: drawn_library cols: Index(['cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type     object
cell_bc       object
cre_id        object
mpra_bc       object
abundance    float64
dtype: object

[debug] pickled df to: permerge_cells_df_c7aa06ec7f774565a4b369c8b8724de4.pkl
[debug] pickled df to: premerge_gt_4ebd2590fb9e4dffa3abfbdd47bf0de2.pkl
[debug] pickled df to: permerge_cells_df_4b7795679ce748afa797d8a1d6f9c914.pkl
[debug] pickled df to: premerge_gt_4a8cc13d750641d2bf3e3e2be05d88f3.pkl

scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
dtype: object
scMPRAforge: INFO: C.5: cells_df cols: Index(['cre_id', 'cell_type', 'true_mean'], dtype='object'), types: cre_id       string[python]
cell_type    string[python]
true_mean           float64
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
dtype: object
scMPRAforge: INFO: C.5: cells_df cols: Index(['cre_id', 'cell_type', 'true_mean'], dtype='object'), types: cre_id       string[python]
cell_type    string[python]
true_mean           float64
dtype: object

[debug] pickled df to: permerge_cells_df_2f9a242d70f94267bd0550d22d11c873.pkl
[debug] pickled df to: premerge_gt_e01e1228b41440f19a2906144ed2c660.pkl
[debug] pickled df to: permerge_cells_df_ba45c8b686c740f4b4aae36e46c280ab.pkl
[debug] pickled df to: premerge_gt_0ee6c3cdca0a491299332a3d3e9ed250.pkl
[debug] pickled df to: postmerge_7df7fbb3e5844149a02d4a9c5c4d36f8.pkl
[debug] pickled df to: postmerge_31cba74ef25d475b937393398a5e3190.pkl

scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'true_mean'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
true_mean           float64
dtype: object
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'true_mean'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
true_mean           float64
dtype: object
scMPRAforge: INFO: D 150107
scMPRAforge: INFO: D 150334

[debug] pickled df to: postmerge_693955e8e5754eadb5b10440e1f37606.pkl
[debug] pickled df to: postmerge_5cb74d9b6ec2409ba85fe5fba38cd4da.pkl

scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'true_mean'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
true_mean           float64
dtype: object
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'true_mean'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
true_mean           float64
dtype: object
scMPRAforge: INFO: D 144995
scMPRAforge: INFO: D 151477
2026-01-23 15:38:30,105 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-9a1f61bd9309385678af65ffcc1606b6
State:     executing
Task:  <Task '_simulate_transfection_helper-9a1f61bd9309385678af65ffcc1606b6' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...               mpra_bc true_mean\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAACCCGCCTC       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATGCCCGGA       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAGGCACTAT       NaN\\n6       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAGACTGAAT       NaN\\n7       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAGTAACCAG       NaN\\n...                ...                   ...  ...                   ...       ...\\n781097       reference  AAAAAAAAAAAAGGGCCACG  ...  AAAAAAAAAAAATCAGCTAG       NaN\\n781134       reference  AAAAAAAAAAAAGGGCCAGA  ...  AAAAAAAAAAAATCAGAAGG       NaN\\n781248       reference  AAAAAAAAAAAAGGGCCATA  ...  AAAAAAAAAAAATCAGATCA       NaN\\n781368       reference  AAAAAAAAAAAAGGGCCCCC  ...  AAAAAAAAAAAATCAGCTAG       NaN\\n781622       reference  AAAAAAAAAAAAGGGCCGCC  ...  AAAAAAAAAAAATCAGATGT       NaN\\n\\n[150107 rows x 5 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5093, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5848, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5834, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

2026-01-23 15:38:30,118 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-0f319e040d98e49e886ff3d3359ef97e
State:     executing
Task:  <Task '_simulate_transfection_helper-0f319e040d98e49e886ff3d3359ef97e' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...               mpra_bc true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAACTTACAA       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAACTTTAGG       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATTGGTAGT       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATCGTCTAC       NaN\\n6       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAAGAAGCAT       NaN\\n...                ...                   ...  ...                   ...       ...\\n780221       reference  AAAAAAAAAAAAGGGCATAG  ...  AAAAAAAAAAACATTCACGG       NaN\\n780560       reference  AAAAAAAAAAAAGGGCCAGA  ...  AAAAAAAAAAACATTCACTA       NaN\\n780600       reference  AAAAAAAAAAAAGGGCCAGC  ...  AAAAAAAAAAAACGGAGATC       NaN\\n781032       reference  AAAAAAAAAAAAGGGCCCTG  ...  AAAAAAAAAAACATTCCGAA       NaN\\n781048       reference  AAAAAAAAAAAAGGGCCCTT  ...  AAAAAAAAAAACATTCAGGA       NaN\\n\\n[150334 rows x 5 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5093, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5848, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5834, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

2026-01-23 15:38:30,311 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-f23fd9f2372fba1016ccc8db9032ae72
State:     executing
Task:  <Task '_simulate_transfection_helper-f23fd9f2372fba1016ccc8db9032ae72' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...               mpra_bc true_mean\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAACAGAACCTC       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATATTGGGC       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAGCGAAGAG       NaN\\n5       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAAAAGGCTC       NaN\\n6       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAACGAATTCG       NaN\\n...                ...                   ...  ...                   ...       ...\\n778520       reference  AAAAAAAAAAAAGGGCCAGA  ...  AAAAAAAAAAAATCCCAGGA       NaN\\n778840       reference  AAAAAAAAAAAAGGGCCCGG  ...  AAAAAAAAAAAATCCCCAGC       NaN\\n778854       reference  AAAAAAAAAAAAGGGCCCGT  ...  AAAAAAAAAAAATCCCAGAT       NaN\\n778973       reference  AAAAAAAAAAAAGGGCCCTT  ...  AAAAAAAAAAACCAATGGTC       NaN\\n779055       reference  AAAAAAAAAAAAGGGCCGAT  ...  AAAAAAAAAAAATCCATTTA       NaN\\n\\n[144995 rows x 5 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5093, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5848, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5834, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

2026-01-23 15:38:30,343 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-26c29bb93bbab4d5845866cdf660256d
State:     executing
Task:  <Task '_simulate_transfection_helper-26c29bb93bbab4d5845866cdf660256d' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...               mpra_bc true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATGAGGCGG       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATAATAAGG       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAAGTCTCGG       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAATGATGAA       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAACTGCCTGG       NaN\\n...                ...                   ...  ...                   ...       ...\\n779391       reference  AAAAAAAAAAAAGGGCATGA  ...  AAAAAAAAAAAATCCCGCCT       NaN\\n779767       reference  AAAAAAAAAAAAGGGCCAGG  ...  AAAAAAAAAAACCAAGCACA       NaN\\n779785       reference  AAAAAAAAAAAAGGGCCATC  ...  AAAAAAAAAAACCAAGAGCG       NaN\\n780122       reference  AAAAAAAAAAAAGGGCCGCA  ...  AAAAAAAAAAAACGGGATAG       NaN\\n780238       reference  AAAAAAAAAAAAGGGCCGGT  ...  AAAAAAAAAAACCAAGCCCC       NaN\\n\\n[151477 rows x 5 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5093, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5848, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5834, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

scMPRAforge: INFO: A: drawn_library cols: Index(['cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type     object
cell_bc       object
cre_id        object
mpra_bc       object
abundance    float64
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
dtype: object
scMPRAforge: INFO: C.5: cells_df cols: Index(['cre_id', 'cell_type', 'true_mean'], dtype='object'), types: cre_id       string[python]
cell_type    string[python]
true_mean           float64
dtype: object

[debug] pickled df to: permerge_cells_df_3db01db8a3b04b48904b4d6c5c5cafd4.pkl
[debug] pickled df to: premerge_gt_487170744b554bb8b52c89b69070ad90.pkl
[debug] pickled df to: postmerge_2e81c4e9326e4d348a17b45df0f1cbaf.pkl

scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'cre_id', 'mpra_bc', 'true_mean'], dtype='object'), types: cell_type    string[python]
cell_bc              object
cre_id       string[python]
mpra_bc              object
true_mean           float64
dtype: object
scMPRAforge: INFO: D 145865
2026-01-23 15:38:31,385 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-e869418ced61dd6f816b27ee4dfbe4f5
State:     executing
Task:  <Task '_simulate_transfection_helper-e869418ced61dd6f816b27ee4dfbe4f5' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...               mpra_bc true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAAGTCAGAT       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAACTCGCCT       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAAGCAGGGGG       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAACACTCGTAA       NaN\\n5       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...  AAAAAAAAAAAATAGGATCA       NaN\\n...                ...                   ...  ...                   ...       ...\\n782820       reference  AAAAAAAAAAAAGGGCACAT  ...  AAAAAAAAAAAATCATCGGT       NaN\\n782910       reference  AAAAAAAAAAAAGGGCACCT  ...  AAAAAAAAAAAATCATAGGT       NaN\\n783106       reference  AAAAAAAAAAAAGGGCAGCA  ...  AAAAAAAAAAAATCAGTCAG       NaN\\n783871       reference  AAAAAAAAAAAAGGGCCATT  ...  AAAAAAAAAAAACGCATTCG       NaN\\n784051       reference  AAAAAAAAAAAAGGGCCCCT  ...  AAAAAAAAAAAATCATCTCC       NaN\\n\\n[145865 rows x 5 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5093, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5848, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5834, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

In [27]:
cells_df=scm.load_df_pickle_debug("permerge_cells_df_ba45c8b686c740f4b4aae36e46c280ab.pkl")
#cells_df=scm.cast_string_keys(cells_df,["cell_type", "cre_id"])
ground_truth=scm.load_df_pickle_debug("premerge_gt_0ee6c3cdca0a491299332a3d3e9ed250.pkl")
#ground_truth=scm.cast_string_keys(ground_truth,["cell_type", "cre_id"])

[debug] loaded df from: permerge_cells_df_ba45c8b686c740f4b4aae36e46c280ab.pkl
[debug] loaded df from: premerge_gt_0ee6c3cdca0a491299332a3d3e9ed250.pkl

In [28]:
cells_df.merge(ground_truth,
                on=["cell_type","cre_id"],
                validate="many_to_one",
                how="left",
                indicator=True)

,cell_type,cell_bc,cre_id,mpra_bc,true_mean,_merge
0,Cardiomyocytes,AAAAAAAAAAAAAAAAAAAA,inactive_13_b,AAAAAAAAAAAATGAGGCGG,NaN,left_only
1,Cardiomyocytes,AAAAAAAAAAAAAAAAAAAA,inactive_163,AAAAAAAAAAAATAATAAGG,NaN,left_only
2,Cardiomyocytes,AAAAAAAAAAAAAAAAAAAA,Gata4_chr14_5776,AAAAAAAAAAAAAGTCTCGG,NaN,left_only
3,Cardiomyocytes,AAAAAAAAAAAAAAAAAAAA,Lama1_chr17_7784,AAAAAAAAAAAAATGATGAA,NaN,left_only
4,Cardiomyocytes,AAAAAAAAAAAAAAAAAAAA,inactive_20,AAAAAAAAAAAACTGCCTGG,NaN,left_only
...,...,...,...,...,...,...
780521,reference,AAAAAAAAAAAAGGGCCTTA,inactive_86_b,AAAAAAAAAAACAAGCTAAC,0.019311,both
780522,reference,AAAAAAAAAAAAGGGCCTTA,inactive_196,AAAAAAAAAAAATCCATATA,0.019311,both
780523,reference,AAAAAAAAAAAAGGGCCTTA,inactive_207_b,AAAAAAAAAAACCACGCAGT,0.019311,both
780524,reference,AAAAAAAAAAAAGGGCCTTA,inactive_61,AAAAAAAAAAAAGATAGGGG,0.019311,both
780525,reference,AAAAAAAAAAAAGGGCCTTA,inactive_134_b,AAAAAAAAAAACAGAGCTTA,0.019311,both

In [32]:
cells_df.sort_values(by=['cre_id', 'cell_type'])

,cell_type,cell_bc,cre_id,mpra_bc
170,Cardiomyocytes,AAAAAAAAAAAAAAAAAATC,Bend5_chr4_8168,AAAAAAAAAAAAAAAAATGC
440,Cardiomyocytes,AAAAAAAAAAAAAAAAACTG,Bend5_chr4_8168,AAAAAAAAAAAAAAAAAAAG
1991,Cardiomyocytes,AAAAAAAAAAAAAAAACTGT,Bend5_chr4_8168,AAAAAAAAAAAAAAAAACGA
2265,Cardiomyocytes,AAAAAAAAAAAAAAAAGATG,Bend5_chr4_8168,AAAAAAAAAAAAAAAAACGC
9237,Cardiomyocytes,AAAAAAAAAAAAAAAGAACG,Bend5_chr4_8168,AAAAAAAAAAAAAAAAACAG
...,...,...,...,...
779437,reference,AAAAAAAAAAAAGGGCATTA,ubcP,AAAAAAAAAAAACGTGGGAT
780065,reference,AAAAAAAAAAAAGGGCCGAT,ubcP,AAAAAAAAAAAACGTGTGGA
780283,reference,AAAAAAAAAAAAGGGCCGTT,ubcP,AAAAAAAAAAAACGTGTGTC
780363,reference,AAAAAAAAAAAAGGGCCTAC,ubcP,AAAAAAAAAAAACGTGTAGC
780497,reference,AAAAAAAAAAAAGGGCCTGA,ubcP,AAAAAAAAAAAACGTGTACG

In [33]:
ground_truth.sort_values(by=['cre_id', 'cell_type'])

               cre_id                cell_type  true_mean
0     Bend5_chr4_8168  EpiblastPrimitiveStreak   0.028050
1     Bend5_chr4_8168       ExEndodermParietal   0.034062
2     Bend5_chr4_8168       NeuroectodermBrain   0.019509
3     Bend5_chr4_8168          SurfaceEctoderm   0.019097
4     Bend5_chr4_8168                reference   0.046651
...               ...                      ...        ...
1457             ubcP                 Mesoderm  11.870977
1458             ubcP       NeuroectodermBrain  11.051645
1459             ubcP     NeuroectodermRostral  10.442030
1460             ubcP          SurfaceEctoderm  14.532331
1461             ubcP                reference  38.759719

[4386 rows x 3 columns]

In [36]:
cells_df[['cre_id', 'cell_type']].drop_duplicates()

                  cre_id       cell_type
0          inactive_13_b  Cardiomyocytes
1           inactive_163  Cardiomyocytes
2       Gata4_chr14_5776  Cardiomyocytes
3       Lama1_chr17_7784  Cardiomyocytes
4            inactive_20  Cardiomyocytes
...                  ...             ...
636083       inactive_60       reference
636267       inactive_58       reference
636345  Col5a1_chr2_2575       reference
637686     inactive_17_b       reference
639254       inactive_79       reference

[6239 rows x 2 columns]

In [35]:
ground_truth[['cre_id', 'cell_type']].drop_duplicates()

               cre_id                cell_type
0     Bend5_chr4_8168  EpiblastPrimitiveStreak
1     Bend5_chr4_8168       ExEndodermParietal
2     Bend5_chr4_8168       NeuroectodermBrain
3     Bend5_chr4_8168          SurfaceEctoderm
4     Bend5_chr4_8168                reference
...               ...                      ...
4381   inactive_207_b                 Mesoderm
4382   inactive_207_b       NeuroectodermBrain
4383   inactive_207_b     NeuroectodermRostral
4384   inactive_207_b          SurfaceEctoderm
4385   inactive_207_b                reference

[4386 rows x 2 columns]